### ISSUE TITLE
How to config pact log path ?

### ISSUE THREAD

**Issue by KenWang007** [pact-foundation/pact-net#131]
Hi brother

Currently the default pact provider end log path is base directory which our application run(bin\Debug\log\pact.log) , how to change the log output directory to specific path and give a better file name ?

thanks.

**Comment by neilcampbell** [comment]
Hi @KenWang007 
An example of this is in the readme https://github.com/pact-foundation/pact-net#2-describe-and-configure-the-pact-as-a-service-consumer-with-a-mock-service

```
PactBuilder = new PactBuilder(new PactConfig { PactDir = @"..\pacts", LogDir = @"c:\temp\logs" });
```

**Comment by neilcampbell** [comment]
Also you can't change the filename

**Comment by KenWang007** [comment]
Thanks for your response, i saw it before , and it's consumer log directory rather than provider , i mean how to config provider log path. Currently we have single front-end and back-end , we use pact.js in front-end(consumer) and use PactNet in back-end(provider),  front-end generate the contract json file and backend-end call actual service to verify it. So i want to config log output path for back-end and i didn't found any parameters to change the log path, does it support it ?

`var config = new PactVerifierConfig
            {
                Outputters = new List<IOutput>
                {
                    new ContractTestOutput(output)
                }
            };`

`IPactVerifier pactVerifier = new PactVerifier(config);
            pactVerifier.ServiceProvider("Event API", serviceUri)
                .HonoursPactWith("Event API Consumer")
                .PactUri(contractFilePath).Verify();`

**Comment by neilcampbell** [comment]
Sorry my mistake, didn't read properly. There is no way to set a log file path for the pact verifier, as no log file is generated by the ruby standalone core.

You can create an Outputter like you have done above, however when doing this you take full control of how and where the file is written.

Does that help?

**Comment by KenWang007** [comment]
Yes, thanks for your response., thanks very much.

**Comment by bethesque** [comment]
Actually, there is a log file when verifying. It contains all the requests and the responses. The configuration is just not exposed in the CLI. I can add it if you would like?
