### ISSUE TITLE
No interaction/internal 500 error

### ISSUE THREAD

**Issue by ardz** [pact-foundation/pact-net#132]
Ok so this perhaps isn't an issue but I can't seem to find any additional info on this. I've setup the mock with the following:

               `MockProviderService.Given($"There is a person with id '{personId}'")
                .UponReceiving($"A GET request to retrieve person with id '{personId}'")
                .With(new ProviderServiceRequest
                {
                    Method = HttpVerb.Get,
                    Path = "/api/person",
                    Headers = new Dictionary<string, object>
                    {
                        {"Accept", "application/json"}
                    }
                })
                .WillRespondWith(new ProviderServiceResponse
                {
                    Status = 200,
                    Headers = new Dictionary<string, object>
                    {
                        {"Content-Type", "application/json; charset=utf-8"}
                    },
                    Body = new
                    {
                        personId = 1,
                        fullName = "Bob Smith"
                    }
                });`

I know I'm not actually passing the personId into the request yet...

However doing the GET just returns the following:

![image](https://user-images.githubusercontent.com/6310248/33995509-1f9a431c-e0d6-11e7-94a5-308e3b42bdc6.png)

Any ideas 😕 

Thanks!

**Comment by neilcampbell** [comment]
Are you sending the `Accept: application/json` header in the request?

**Comment by bethesque** [comment]
If it was just the content type that was wrong, you'd get an interaction in the `interaction_diffs` array, and it would show you that the content type was wrong. I would infer from this that the interaction was not set up at all at the time that the GET request was made.

**Comment by ardz** [comment]
OK, so my buddy has worked out what the issue was:

`            // needed this
            MockProviderService.Start();

            #region Pact Mock Provider Setup

            MockProviderService.Given("There is a something with id 'tester'")
                .UponReceiving("A GET request to retrieve the something")
                .With(new ProviderServiceRequest
                {
                    Method = HttpVerb.Get,
                    Path = "/somethings/tester",
                    Headers = new Dictionary<string, object>
                    {
                        { "Accept", "application/json" }
                    },
                    // and this
                    Query = ""

![image](https://user-images.githubusercontent.com/6310248/34040126-404db1b6-e18a-11e7-9626-bdd9630d31d7.png)

The code example here [https://github.com/pact-foundation/pact-net](url) doesn't show this however...

**Comment by neilcampbell** [comment]
Start shouldn't be needed, as calling `PactBuilder.MockService(...)` will give you a hot (running) mock provider service. See https://github.com/pact-foundation/pact-net/blob/master/PactNet/PactBuilder.cs#L86. That is only really used if you want to restart the service.

You definitely had a running mock provider service, as it's responding to HTTP requests and giving you a 500.

**Comment by ardz** [comment]
@neilcampbell yeah, removed the Start Method call.

**Comment by ardz** [comment]
@neilcampbell Neil, why is it that I need to include:

Query = ""

In the ProviderServiceRequest parameters? I notice in all your code examples you don't have this but it throws a 500 error if I don't include it?

**Comment by neilcampbell** [comment]
@ardz You don't need the query. I'm not sure why that would be the case. The only real way for me to help any further is if you create a sample of your problem that I can run.
