### ISSUE TITLE
.NET Core Example needed

### ISSUE THREAD

**Issue by Blackbaud-JonathanBell** [pact-foundation/pact-net#133]
I see that pact-net was updated to target .NET Standard to support .NET Core applications.  I think a provider example is needed to illustrate how this should work.

Trying it out, I can't get it to work with the `TestServer` class, which I generally use in my unit test projects.  However,  I get the error: 

`No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 5000`

Am I supposed to use `builder.Build().Run()` or something along those lines to start the server instead?

I know the .NET Core + PACT support is fairly new, so I can't find anything online as far as examples go, and feel that it isn't obvious how this should be setup.

**Comment by neilcampbell** [comment]
Yeah unfortunately we don't have a sample with .NET core in the repo. Definitely agree that it would be great to have one. You'd implement as @daveboyle1 mentioned in https://github.com/pact-foundation/pact-net/issues/78#issuecomment-352548020. Once you get it all working would you mind creating a PR to add a simple .NET core sample into the Samples dir?

**Comment by tdshipley** [comment]
@neilcampbell I have been working on porting the https://github.com/DiUS/pact-workshop-ruby-v2 to .NET Core using PactNet. It is not finished yet but perhaps when it is you can link from the docs? https://github.com/tdshipley/pact-workshop-dotnet-core-v1

**Comment by neilcampbell** [comment]
@tdshipley Sorry I have been slow to respond.
Awesome, yeah happy to do that when you are done. Just send through a README.md PR and I will merge it in 😄
