### ISSUE TITLE
Version 2 on .NET Core

### ISSUE THREAD

**Issue by rafsojka** [pact-foundation/pact-net#138]
I looked into integrating PactNet into my team CI pipeline following [the steps](https://github.com/tdshipley/pact-workshop-dotnet-core-v1).
I've managed to create a solution working locally for one of our endpoints.

There are however a few points that I wanted to clarify:
- Is there any advised solution for using PackNet.Windows and PackNet.Linux side by side in the project as we are developing on Windows but CI uses Linux on Docker?
- Is there any other way for provider state setup than starting a web server with a middleware?
- I can see that Version 1 used to expose a way to set up a tear down method for provider state, cannot see it anymore in Version 2. Is that still possible?
- Is there a way to pass parameters to provider state setup Actions?
- I only managed to make the provider state setup working when I've changed my Actions to run synchronously. Is there a way to use async methods there?

**Comment by daveboyle1** [comment]
the middleware intercepts the provider state's requests so I think you will still need that. for teardown, I just made sure my datacontext was cleared before adding new data for each particular interaction. Hope that helps on a couple of questions.





Sent from OPPO Mail
On rafsojka <notifications@github.com>, 23 Feb 2018 3:01 am wrote:

I looked into integrating PactNet into my team CI pipeline following the steps<https://github.com/tdshipley/pact-workshop-dotnet-core-v1>.
I've managed to create a solution working locally for one of our endpoints.

There are however a few points that I wanted to clarify:

  *   Is there any advised solution for using PackNet.Windows and PackNet.Linux side by side in the project as we are developing on Windows but CI uses Linux on Docker?
  *   Is there any other way for provider state setup than starting a web server with a middleware?
  *   I can see that Version 1 used to expose a way to set up a tear down method for provider state, cannot see it anymore in Version 2. Is that still possible?
  *   Is there a way to pass parameters to provider state setup Actions?
  *   I only managed to make the provider state setup working when I've changed my Actions to run synchronously. Is there a way to use async methods there?

**Comment by bethesque** [comment]
It is much safer to clear everything at the start of an interaction than to tear specific data down at the end of an interaction. The provider state set up url can be in a completely separate web application - it just needs to point to the same datasource.

**Comment by bethesque** [comment]
Given that the set up must be performed synchronously before the interaction can be replayed, I don't see any way to make it fun asynchronously.

What parameters are you interested in passing?

**Comment by bethesque** [comment]
Fun = run! No way to make it fun either ;-)

**Comment by neilcampbell** [comment]
_Is there any advised solution for using PackNet.Windows and PackNet.Linux side by side in the project as we are developing on Windows but CI uses Linux on Docker?_

You should be able to just install both packages and PactNet will determine which one to load based on the platform the code is running on. Let us know if you hit any issues here.

_Is there any other way for provider state setup than starting a web server with a middleware?_

What @bethesque said above. If you want to setup your provider state within the same server, you don't technically require middleware, however you do need the web server running an the endpoints need to exist and get registered using some other mechanism.

_I can see that Version 1 used to expose a way to set up a tear down method for provider state, cannot see it anymore in Version 2. Is that still possible?_

What @bethesque said above.

_Is there a way to pass parameters to provider state setup Actions?_

No, there is no support for params at this point in time.

_I only managed to make the provider state setup working when I've changed my Actions to run synchronously. Is there a way to use async methods there?_

Are you referring to the provider state actions? Is there a specific reason to make them async? As Beth mentioned you would still need to await for them to complete before continuing. Either way though you are completely in control of how you write the provider state string to action resolution and execution.

**Comment by rafsojka** [comment]
Thanks @daveboyle1 @bethesque @neilcampbell for your answers to my questions.

**What parameters are you interested in passing?**
When asking I had in mind a solution similar to https://github.com/techtalk/SpecFlow/wiki/Step-Definitions
I could see a value in it to make the provider state setups more specific.
