### ISSUE TITLE
My PACT file suggests to use GET method. But verify method used unsupported POST method.

### ISSUE THREAD

**Issue by piuskurianau** [pact-foundation/pact-net#145]
Pact::ProviderVerifier::SetUpProviderStateError:
Error setting up provider state ...
response status=405 response body={"Message":"The requested resource does not support http method 'POST'."}

{
  "consumer": {
    "name": "Consumer"
  },
  "provider": {
    "name": "Something API"
  },
  "interactions": [
    {
      "description": "A GET request to retrieve Invoice Item with NMI '1234567890'",
      "providerState": "There is a Invoice Item with NMI '1234567890'",
      "request": {
        "method": "get",
        "path": "mypath/3",
        "headers": {
          "Accept": "application/json"
        }
      },
      "response": {
        "status": 200,
        "headers": {
          "Content-Type": "application/json; charset=utf-8"
        },
        "body": [
          {
            "NMI": "1234567890",
            "FromDate": "2017-04-01T00:00:00",
            "ToDate": "2017-04-30T00:00:00",
            "Category": "Environmental Schemes",
          },
          {
            "NMI": "1234567890",
            "FromDate": "2017-04-01T00:00:00",
            "ToDate": "2017-04-30T00:00:00",
            "Category": "Environmental Schemes",
          }
        ]
      }
    }
  ],
  "metadata": {
    "pactSpecification": {
      "version": "1.0.0"
    }
  }
}

**Comment by bethesque** [comment]
The name of the error is `Pact::ProviderVerifier::SetUpProviderStateError:` It's the provider state set up endpoint that is returning the error, not the provider endpoint. Your provider state set up endpoint should accept a POST.
