### ISSUE TITLE
How to mock My.User.IsInRole() in Unit Test MVC .net

### ISSUE THREAD

**Issue by MoqTest** [pact-foundation/pact-net#146]
This is my controller method (written in VB, C# is acceptable too):
      If My.User.IsInRole("Administration") Then
               result = "success"
      End If
I got exception error on My.User.IsInRole(), how can I mock the object in this case? Thanks.

**Comment by neilcampbell** [comment]
Hi @MoqTest 
Without more info about your specific use case, I can't really help here.

**Comment by MoqTest** [comment]
Thanks it's been fixed. See the detail in the other issue I created.
