### ISSUE TITLE
Purpose of assertions and verifyInteractions in Pact consumer side project

### ISSUE THREAD

**Issue by bbat** [pact-foundation/pact-net#150]
Could you explain why do we need to make assertions in tests in the consumer side project please ?

We are sending a request to a mock server that we have configured few lines ahead. So we are sure that the response will be the one expected, isn't it ?

I also don't understand what is the purpose of the verifyInteractions() at the end of the test.

I think I have missed something... please help me.

**Comment by neilcampbell** [comment]
Hi @bbat. Yeah no problems at all.
The pact mock provider service exists to just respond to http request in the way you configure it to respond, however it does not check that your client code handles that response in the correct way. The assertions in the test, basically are just business logic test to check the client does the correct things with the response.

verifyInteractions() just ensures that all registered interactions on mock provider service, were actually seen by the mock provider service when the test runs.

Does that make sense?

**Comment by bbat** [comment]
Yes, thanks, it is clear for me now.

In fact,for the moment, we just want to generate the pact and test the provider side. 

So, we have created a "fake" consumer client to send the request to the mock provider service instead of using the "real" consumer client. So, if I understand, assertions are useless in this case. Is it right ?

Tomorrow, we should add assertions in the consumer test when we use the "real" consumer client.
