### ISSUE TITLE
Running tests in docker

### ISSUE THREAD

**Issue by rgparkins** [pact-foundation/pact-net#154]
Submitting as an issue as I cant seem to get the mock service to run in Docker. I think its due to the container its running in is hosted on 0.0.0.0 which is the default address that the service is set to when starting the mock. This means that the mock service can never run.

Have run this pst a few people and it seems like an issue on the current version `IpAddres.Any` or `IpAddress.Loopback`

Works fine when running on Mac. Not a big docker user so please close if its my misunderstanding

**Comment by neilcampbell** [comment]
Hi @rgparkins 
Thanks for submitting this. I haven't personally tried running it in docker. Is it docker on windows, mac or linux?

Are you able to create an example that can reproduce what you are seeing? Also happy to accept PRs if you want to troubleshoot this further.

Thanks,
Neil

**Comment by bethesque** [comment]
If you work out what needs to happen to make this work, let me know if you need any changes to the ruby standalone.

**Comment by rgparkins** [comment]
Thanks guys, let me get something either detailed or maybe PR

**Comment by rgparkins** [comment]
Ok, so I restarted my machine and cannot get the docker tests to fail! So apologies but I think this may be a non issue and the mock service DOES IN FACT start up and doesn't clash with the container IP's

**Comment by bethesque** [comment]
Good to know. I find I have issues with docker containers and IPs if I move from my work to home wifi - I think the DNS gets all confused.
