### ISSUE TITLE
Pacts Folder Missing

### ISSUE THREAD

**Issue by Trazarw** [pact-foundation/pact-net#155]
Hello guys I am trying to generate the pact files in the consumer side.

For some strange reason the logs folder is generated but not the pact one.

It does not do anything if I try to use the default location or if I set a new path.

I am using PactNet 2.3.1 and PactNet.Window 2.3.1 on net451

Anybody facing this issue?

**Comment by bethesque** [comment]
Did the tests pass? The pact files will only be generated if you made all the correct calls to the mock service.

**Comment by Trazarw** [comment]
Hey sorry for the late response, it is fixed now, inheriting from a xUnit IClassFixture<> works fine, but using a pact instance in class scope does not work :/

**Comment by syedhassaanahmed** [comment]
@bethesque I have the same issue with PactNet 2.4.6 on Windows and `netcoreapp3.0`. The tests pass, logs are generated but Pacts folder is missing. 

> inheriting from a xUnit IClassFixture<> works fine, but using a pact instance in class scope does not work

@Trazarw Can you please elaborate a bit more on what do you mean by above?

**Comment by neilcampbell** [comment]
@syedhassaanahmed Do you have a call to `PactBuilder.Build();`? That is what write the pact file

**Comment by syedhassaanahmed** [comment]
Hi @neilcampbell Many thanks for the quick response. I had a call to `PactBuilder.Build();` in a `Dispose()` but the Class didn't implement `IDisposable` :) Fixing that solved the issue.

**Comment by neilcampbell** [comment]
Ah yep, that will do it. Thanks for replying with your fix, hopefully it will help someone else.
