### ISSUE TITLE
Can array property be empty and still validate? 

### ISSUE THREAD

**Issue by chwolfe** [pact-foundation/pact-net#156]
In the sample code below, how can I tell pact-net that the Societies property can be either an empty (not null) array OR it contains entries as specified? Thanks! 

                .WillRespondWith(new ProviderServiceResponse
                {
                    Status = 200,
                    Headers = new Dictionary<string, object>
                    {
                        { "Content-Type", "application/json; charset=utf-8" }
                    },
                    Body = new TypeMatcher(new
                    {
                        CustomerId = customerId,
                        CurrentStatus = "Active",
                        OnProfessionalLeave = false,
                        Societies = new[]
                        {
                            new {
                                SocietyPartnerId = "1010068",
                                JoinDate = "2018-07-11T03:07:00",
                                CurrentStatus = "Active"
                            } 
                            
                        }
                        
                    })

**Comment by bethesque** [comment]
Hi @chwolfe. This is not supported, and here is the reason why: https://docs.pact.io/faq#why-is-there-no-support-for-specifying-optional-attributes

**Comment by chwolfe** [comment]
@bethesque, Thanks for the quick response. I appreciate the feedback. - Chris
