### ISSUE TITLE
Questions - Contract tests vs functional tests

### ISSUE THREAD

**Issue by mattfrear** [pact-foundation/pact-net#158]
Hello

We are still evaluating Pact tests in our organisation and have so far written consumer and provider tests, thanks mostly to tdshipley's pact workshop in .NET Core. (Also thanks to you guys for pact-net!)

I'm still struggling to get my head around the Pact tests and what value they provide. I feel like I'm missing something. Now that we have a working implementation I have a few questions, if I may.

1. The best practices over at pact.io has this specific example https://docs.pact.io/best_practices/consumer/contract_tests_not_functional_tests
```
Given that username "bad_username" is invalid
When "creating a user with an invalid username"
  POST /users { "username": "bad_username", ... }
Then
  Response is 400 Bad Request
  Response body is { "error": "<any string>" }
```
I can't see how the provider-state API middleware could accomplish this sort of setup. Maybe the ProviderStateMiddleware would need to live in my API under test instead of in a separate provider state API, but even then I don't think it would be possible.
2. According to https://docs.pact.io/readme
> Pact tests should be data independent. Pact tests are best when successful verification doesn’t depend on the specific data that the provider returns.

So let's say I have a CRUD app which returns a 201 and the ID of the created entity when I POST to it. My consumer tests just need to check that an ID is returned, and that it's a GUID. They don't care what the ID is. My provider tests need to confirm that they return a GUID too.
What would that look like in my pact.json? How about:
```
      "response": {
        "status": 201,
        "headers": {
          "Content-Type": "application/json; charset=utf-8"
        },
        "body": {
          "id": "b106887d-7edb-47fd-a1e8-fbe0abdd84b6"
        }
      }
```
This seems wrong, since I'm tying my test to a specific id. And how would I set that up with provider state?

Any clarification appreciated.

**Comment by neilcampbell** [comment]
Hey @mattfrear,

1. You can run the provider state api inside your api or as a external api, it's completely up to you. I usually run it inside the same api personally as I find it makes things easier. There is an example of this here https://github.com/pact-foundation/pact-net/tree/master/Samples/EventApi/Provider.Api.Web.Tests. Hopefully this kind of approach should work with .NET core as well.

2. In this example you would probably use a matcher to do this. See https://github.com/pact-foundation/pact-net/blob/master/Samples/EventApi/Consumer.Tests/EventsApiConsumerTests.cs#L260 and https://docs.pact.io/getting_started/matching#pact-matching-features

Hopefully this is helpful!

**Comment by bethesque** [comment]
@mattfrear I think that is just a poorly worded example. There is nothing in a provider state that would generally change the way that the validation was implemented (unless there was something like a length that could be configured). I'll see about updating that.

**Comment by neilcampbell** [comment]
+1 to what @bethesque said. In the example `Given that username "bad_username" is invalid` we would likely just be creating an invalid user (as per the rules of your domain). In this instance it would probably be a no-op or ensuring there is no user called bad_username in the database, so the provider code would exercise the correct flow.

**Comment by mattfrear** [comment]
Thanks for the clarification @bethesque and @neilcampbell . Yeah I think that example is not helpful. The way it is written is "this is what you should strive for", yet it seems like it's something that would be difficult or impossible to implement.

**Comment by mattfrear** [comment]
Thanks @bethesque , yes that's much better 👍
