### ISSUE TITLE
Selectively adding Authorization header to provider tests - NETCore 2.1

### ISSUE THREAD

**Issue by JonyTek** [pact-foundation/pact-net#167]
Hi,

I am wondering what is the recommended approach for adding/updating of a bearer token?

I saw that within the sample in this repo it is being done via middleware but the latest netcore version does not call through the middleware before making the request in my producer tests. I quite liked this approach as it clear from the consumer tests what your intent is when you add a replace token in the header.

I know that this can be done via `PactVerifierConfig.CustomHeader` but this is for all requests and does not let me selectively apply this to specific interactions.

Thanks in advance.

**Comment by JonyTek** [comment]
Thanks for the reply.

Do you mean that the token generation needs to happen in ruby?

I do need to find a solution so I would be happy to take a look. Is there a
PR or example that I may be able to use as a reference?

**Comment by neilcampbell** [comment]
@JonyTek I haven't been doing any .NET lately, so I'm a bit out of the loop with latest netcore. Does it no longer support middleware? If it supports middleware, when in the lifecycle does the middleware run now?

**Comment by bethesque** [comment]
@JonyTek The modification of the request needs to happen in Ruby (as that is the language of the underlying verifier code) Currently, the .net implementation calls out to the "standalone CLI" (a ruby CLI that is packaged in a way that means the machine does not need to have ruby installed). There is a new CLI option called `--custom-middleware` that needs to be able to be set by the .net code. It should contain the full path to a file that defines some Rack middleware that will generate the code and modify the request accordingly.

Here's an example of it's usage.

https://github.com/pact-foundation/pact-provider-verifier/blob/master/spec/integration_with_custom_middleware_spec.rb#L8

Here is an example of some middleware https://github.com/pact-foundation/pact-provider-verifier/blob/master/spec/support/custom_middleware.rb It currently does nothing but print out the provider states that have been passed in via the Rack headers. Here's a quick intro to Rack middleware https://www.amberbit.com/blog/2011/07/13/introduction-to-rack-middleware/

Happy to help out if you get blocked.

**Comment by JonyTek** [comment]
Thanks very much for the help @bethesque but after looking into this I've decided to take another route where I split my tests into authenticated and unauthenticated. It's not the ideal solution but it still allows me to express intent through tests so I'm happy.
