### ISSUE TITLE
Readme usage has bad practice in the examples

### ISSUE THREAD

**Issue by matt-lethargic** [pact-foundation/pact-net#169]
Looking through your readme file you have written an example client using

    using (var client = new HttpClient { BaseAddress = new Uri(BaseUri) })

creating a new instance of HttpClient on every request is bad practice. The [Microsoft docs](https://docs.microsoft.com/en-gb/dotnet/api/system.net.http.httpclient?view=netframework-4.7.1) state

> HttpClient is intended to be instantiated once and re-used throughout the life of an application. Instantiating an HttpClient class for every request will exhaust the number of sockets available under heavy loads. This will result in SocketException errors. 

See [this article](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/) for full explanation.

I think it's wrong to promote, even if accidentally, this way of writing a client.

**Comment by daveboyle1** [comment]
i suspect the reason is for simplicity sake? to illustrate the use of a (could be any) http client. otherwise you'd need to inject and potentially show your DI setup of a http client, which i doubt is the purpose of the example. my 2c anyway. cheers.

**Comment by matt-lethargic** [comment]
I understand the reasons for it, but as with 90% of the examples on the internet that do this people will blindly copy hence why all of the developers where I work think / thought it was the right thing to do!

**Comment by neilcampbell** [comment]
@matt-lethargic Thanks for pointing that out, it's just an oversight from https://github.com/pact-foundation/pact-net/issues/88. I updated the samples and didn't realise it was in the readme. I'll get that updated.
