### ISSUE TITLE
Question/Issue: Support for MTLS (Client cert signing)

### ISSUE THREAD

**Issue by chris-rogala** [pact-foundation/pact-net#170]
We have services that require the request to be signed with an x.509 certificate.  I've looked throughout Pact and PactNet, and I cannot seem to find a place to configure this within the service provider tests.  

I have looked two-way SSL, MTLS and x.509 and I did not find anything.  Am I missing something or is this a know issue?

**Comment by neilcampbell** [comment]
Hi @chris-rogala. As far as I know the ruby standalone we use does not support two way SSL. @bethesque is that correct?

**Comment by bethesque** [comment]
Not currently. It may be possible to [support](http://www.justskins.com/forums/webrick-https-client-authentication-245922.html) it, but I'd argue that it's not really part of the contract, and if it can be configurably turned off for the contract tests, that would be a better option.
