### ISSUE TITLE
Not killing Ruby process will result in an unpredictable state

### ISSUE THREAD

**Issue by bashiransari** [pact-foundation/pact-net#171]
I encountered this weird behavior where pact keeps complaining about having the same interaction in my tests, the error message is:
"An interaction with same description ("A GET request to retrieve the customer") and provider state ("Customer with id 1 exists") but a different response body has already been used. Please use a different description or provider state, or remove any random data in the interaction."

I tried to figure out what is the problem by running different tests, the more I tried to understand the situation it got more confusing for me.
I cloned the pact-net repo and opened PactNet solution and tried to run the "Consumer.Tests" tests, the outcome was weirder now :-)  running those tests, pact was updating the pact file in my original solution instead of updating "event_api_consumer-event_api.json" file !!!

looking into task manager I saw Ruby.exe is running, after killing that process everything got back to normal. 
Reproducing the state is very easy, just run a pact consumer test in debug mode in VS and stop the test before it finished so that PactNet don't get a chance to kill the process, this will put you in an unpredictable state until you kill the Ruby process.
It's interesting every time I run the tests in this state pact will run a new Ruby process but it's still somehow using the state from the other Ruby process

I think this is a major problem, and probably the solution should be some sort of ping from the child process (Ruby script) to the parent process (dotnet test host) or the other way around so that the child process can detect if the parent process is still alive or not, and kill itself if the parent is not alive.

**Comment by bethesque** [comment]
I've used pid files before to get around this issue. Would that be an option @neilcampbell?

**Comment by bashiransari** [comment]
I don't think you can use pid file in windows

**Comment by bethesque** [comment]
Why is that?

**Comment by neilcampbell** [comment]
Yeah this is a known issue listed in the readme. I couldn't find a way around it, so put some details in the readme so others hopefully wouldn't get caught by it. It only happens when debugging the tests and prematurely interrupting the test runner. In this case there is no hook to run code and perform cleanup activities, so the process unfortunately stays alive.
