### ISSUE TITLE
Way to inject dependencies pre web host startup depending on provider state

### ISSUE THREAD

**Issue by stilren** [pact-foundation/pact-net#173]
First of all, thanks for writing a .net implementation of the pact spec! I am looking into implementing pact at my company (predominantly services written in .net) and have spent time trying to get this to work in a .net core 2.1 project of ours and had some issues.

The way most of our integration tests are written is that external dependencies (database, other services, external api:s etc) are replaced with mock objects that are able to return fake data at test server startup. This is also from what I can tell most common way of mocking external dependencies in the .net world. 

I was not able to do this with the api provided by pact-net, instead the fake data had to be injected in the middleware as the relevant request is passing through. Is there an api that allows me to iterate over the provider states before starting the server/sending the request? Should there be one? I jotted down some psuedo code do describe what I am after.

```
foreach pact in pacts {
   switch (pact.ProviderState) {
       case 'there is a user called john'
           _mockUserService('john').returns(userobject)
        ...
   }
 _httpClient.sendRequest(pact.request)
}```

**Comment by neilcampbell** [comment]
Hi @stilren 
Sorry for the slow response.
There is an api for doing that, it's probably just a little bit different to what you expect as we use the ruby standalone as the core engine and need a way to interop, which is done via HTTP.

Basically pact will call a HTTP endpoint that you specify at runtime. This can be setup using middleware or whatever mechanism you choose (the readme has an example). From there you can execute your own custom code which in your case would setup the mocks to return the correct fake data.

**Comment by stilren** [comment]
Hi Niel. So what I was after was a way of setting up the mock data before the test server is started which I get now is not how pact.net work since the interop is via http. I have followed the examples of setting up data in the middleware/controller and setup provider states by renaming text files with mock data and pointing my mock services to those files before server start but it feels kind of hacky and might be a hard sell for the other teams.

**Comment by neilcampbell** [comment]
Yeah the text file thing does sound a little hacky. You could use IoC here to register a singleton fake implementation before the server starts and at runtime use the provider state hooks to change the test data that the fake returns depending on the scenario being executed.

**Comment by stilren** [comment]
@neilcampbell Yeah, thats more of what I am after, I guess it could be done at runtime as well as before. Thanks!
