### ISSUE TITLE
Can I specify a folder path with multiple json files as the PactUri?

### ISSUE THREAD

**Issue by mihalios** [pact-foundation/pact-net#180]
I'd like to organise my Interactions into multiple JSON files and have them all run in a single test run.

The original setup of my Pact Verifier looks like this:

`IPactVerifier pactVerifier = new PactVerifier(config);`
`pactVerifier.ProviderState($"{_pactServiceUri}/provider-states")`
            `.ServiceProvider("Provider", _providerUri)`
            `.HonoursPactWith("Consumer")`
            `.PactUri(@"..\..\..\..\pacts\my-single-pact.json")`
            `.Verify();`

And I've tried the following with no luck:

`.PactUri(@"..\..\..\..\pacts")`

`.PactUri(@"..\..\..\..\pacts\*.json")`

**Comment by neilcampbell** [comment]
@mihalios Nah it only works for a single uri. You can however instantiate multiple pact verifiers within the test, each specifying a single pact file.

**Comment by mihalios** [comment]
@neilcampbell Thanks Neil, makes sense. I suppose that even better than creating multiple pact verifiers would be to have each test run a single pact.json.

**Comment by neilcampbell** [comment]
Yeah agreed, I reckon a single test per pact file verification is the way to go.

**Comment by bethesque** [comment]
The underlying CLI allows you to specify a list of pact URLs @neilcampbell

**Comment by neilcampbell** [comment]
Ah really, didn't realise.

**Comment by neilcampbell** [comment]
@mihalios No, just means it's possible if you want to send a PR.
