### ISSUE TITLE
Question: Contract verification - request body is converted to dynamic

### ISSUE THREAD

**Issue by Yuliia-Halytsia** [pact-foundation/pact-net#181]
During contract verification I am not reaching method in controller corresponding to endpoint that is verified. Request body is converted into dynamic parameter for this endpoint:
_public async Task<IHttpActionResult> MethodName( [FromBody] dynamic paramater )_
May this cause a problem during verification process?

**Comment by neilcampbell** [comment]
If you can get that api endpoint working outside of pact by just sending a json http request, then pact should also work.
