### ISSUE TITLE
Can a Consumer use a parameterised provider state?

### ISSUE THREAD

**Issue by mihalios** [pact-foundation/pact-net#182]
Hi Neil, from what I can see in code, that's not possible. Just wanted to know if that's the case and whether there have been any thoughts about adding this functionality?

**Comment by neilcampbell** [comment]
Hi @mihalios. Yes that is correct, there is no support for parameterised provider state.
We have thought about it, however I don't believe the ruby standalone (which is what we use) has support for it at this stage.
