### ISSUE TITLE
Cannot generate pact for multiple providers at once

### ISSUE THREAD

**Issue by uonze** [pact-foundation/pact-net#186]
I have a xUnit test project to generate the pacts for multiple providers (since the consumer interacts with multiple providers).

I'm using xUnit CollectionFixture since I have tests spread across different classes. Each collection represents a provider and on the collection fixture constructor I have the code to init the PactBuilder and get the MockService instance and on the dispose the code to build the Pact file.

What happens is that if I run the tests for each provider separately everything works fine, but if I try to run the tests simultaneously (not necessarily in parallel) the tests fail because the mock service does not respond.

You can simulate this using the consumer sample, just duplicate ConsumerEventApiPact.cs and EventsApiConsumerTests.cs and change to something like users for example, and run the tests. They should fail. But if you run the tests separately (first for events then for users) the tests pass.

I think this happens because the fixture code runs simultaneously for each fixture and somehow the mock service is being stopped.

**Comment by neilcampbell** [comment]
Hi @uonze 
You will need to have each MockService for each of your providers run on a seperate port, otherwise they will clash with one another.

**Comment by uonze** [comment]
That solved the problem. Thank you for the help @neilcampbell
