### ISSUE TITLE
Pact-net package folder appears in VS solution explorer

### ISSUE THREAD

**Issue by mihalios** [pact-foundation/pact-net#189]
I was wondering if this is something specific to Pact-Net. When I add a reference to Pact-Net (either the Windows or Linux version) I notice that VS creates a shortcut for the package in Solution Explorer. 

Consequently this gets picked up by Resharper's Code Inspection, which reports CSS errors in some Ruby .css files. 

Building and running the application and verifying Pacts works fine. 

According to VS, the path to this folder is:

[Main Project path]\pact-win32\ which is non-existent! This is only happening with the Pact-Net package in my project, hence my suspicion that it's unique to Pact-net.

![pact-net-solution-explorer](https://user-images.githubusercontent.com/2817656/54752182-0f667180-4bd5-11e9-9871-1200d52df8f2.png)

EDIT: it appears that this is the folder for which the Solution Explorer shortcut is being created:

packages\pactnet.windows\2.4.5\tools\ **pact-win32** \lib\vendor\ruby\2.2.0\gems\httparty-0.16.2\website\css

**Comment by neilcampbell** [comment]
Yeah it does that. I believe VS adds it as a solution folder when the targets file for that package is added. The targets file contains the configuration that ensures the platform specific ruby core is copied to the build directory and is available to pact-net. See https://github.com/pact-foundation/pact-net/blob/master/Build/windows/PactNet.Windows.targets

**Comment by mihalios** [comment]
So once again, it's a necessary evil because we're relying on the ruby core! *sigh*

Thanks @neilcampbell - closing.
