### ISSUE TITLE
xUnit Tests Duplicated in Linux because of PublishToBroker

### ISSUE THREAD

**Issue by uonze** [pact-foundation/pact-net#190]
This is a very weird issue. On the consumer side tests, when using the pactPublisher.PublishToBroker on Linux the number of xUnit tests get duplicated.

Platform: Linux (in Windows works fine)
Versions:
- Dotnet SDK: 2.2.105
- xUnit: 2.4.0
- PactNet.Linux.x64: 2.4.5

I have the following simple code (I simplified the code to focus on the issue, the pact file is present on the file system):

```
public class ConsumerTest : IClassFixture<Fixture>
{
    private readonly Fixture fixture;

    public ConsumerTest(Fixture fixture)
    {
        this.fixture = fixture;
    }

    [Fact]
    public void Test1()
    {
        Assert.True(true);
    }
}
```

```
public class Fixture : IDisposable
{
    public void Dispose()
    {
        var pactPublisher = new PactPublisher("http://localhost:10400");

        pactPublisher.PublishToBroker(
                    "contract.json",
                    "0.0.1",
                    new List<string> { { "dev" } });
    }
}
```

When I run `dotnet test` I get the following output: `Total tests: 2. Passed: 2. Failed: 0. Skipped: 0`

If I comment the PublishToBroker call:

```
public class Fixture : IDisposable
{
    public void Dispose()
    {
        var pactPublisher = new PactPublisher("http://localhost:10400");

        // pactPublisher.PublishToBroker(
        //            "contract.json",
        //            "0.0.1",
        //            new List<string> { { "dev" } });
    }
}
```

I get: `Total tests: 1. Passed: 1. Failed: 0. Skipped: 0`

On a real implementation of the Consumer side tests what happens is that since the tests are running twice, I get a error because the port to the Pact Mock Server is already being used (the fixture code runs twice).

**Comment by uonze** [comment]
This problem is  not related with pact. Somehow on my  linux machine the firewall was blocking access to the broker. That was causing the issue. Weird enough the xUnit reports to double amount of tests...

**Comment by bennettsolnet** [comment]
I have noticed this too. I think that the actual tests are passing, so you get 2 passes. But when the fixture gets disposed and that fails, the framework counts that as a failure for each test in the class, and adds those failures. So you get 2 successes and 2 failures.

I'm not sure what _should_ happen here. The passing tests should count as passed. The failure in the teardown should probably be a warning or something.
