### ISSUE TITLE
[Question]Consumer tests: same request can expect multiple types of response. Tests failing

### ISSUE THREAD

**Issue by bdelsaz** [pact-foundation/pact-net#191]
Hi
First of all thanks for creating this useful library.

I am trying to build pact tests for a consumer, using:
- NUnit 3.11.0
- Pactnet.Windows 2.4.5
- Visual studio 2017

My setup is as follows; I created a partial class for my tests. On the 'main' file I set up the pact builder and mock service. On separate files which are also part of the partial class, I put my tests.

Here is the gist: 
https://gist.github.com/bdelsaz/72acb92116cb1a4eb50623a68d9b8305

**What I expect**
For the same request, let's call it 'IdentifyPerson', the API can return several responses:
1) The person is found, so it returns a json object
2) The person is not found, so it returns a json object representing an HttpProblem exception
3) One combination of parameters in the person-to-identify object is not supported, so it returns a json object representing a HttpProblem exception
4) A header is missing so an HttpProblem validation exception is returned.

I wanted to test against my real http client ('MyExistingClient.cs') and not write a separate client for the tests, because if the real client changes then you have to maintain it twice and it is possible that we forget to make the changes on the 'test' client.

**What I get**
- All the tests pass except for 'IdentifyMethod_WithCorrectRequest_AndExistingPerson_ShouldMatchPact' (the only one that returns a full json object'. Here I am getting this error:
```
W, [2019-04-01T12:19:16.721211 #29408]  WARN -- : Missing requests:
	POST /api/v1/person/identify
	POST /api/v1/person/identify
```
- The pact only registers the consumer-provider call in which a full json object is returned, which is precisely the test which fails.

**My guesses?**
- Something with NUnit? SetUpOnce and TearDownOnce seem to work as the pact is published
- Does pact net support one API call with multiple possible responses?
- The client makes use of a ValidateJsonOrThrow method that verifies that a proper json object has been received (the request was successful). When a HttpProblem is returned to the client this throws an exception. In order to avoid the tests to fail, I made use of Func<Task> and included the VerifyInteraction inside this thread. Maybe is it a threading issue?
```
            Func<Task> act = async () =>
            {
                //Act
                await _consumer.IdentifyPassengerAsync(
                    $"{_mockProviderServiceBaseUri}/api/v1/",
                    metadata,
                    boardingPass,
                    CancellationToken.None);

                //Assert
                _mockProviderService.VerifyInteractions();
            };
```

Hope my explanation of the problem is clear enough. I would appreciate any help!

**Comment by bdelsaz** [comment]
Well I found the solution. It seems to be a threading thing. If I just catch the exception it like this all the tests pass and all the interactions are registered in the pact. 
`            try
            {
                //Act
                await _consumer.IdentifyPersonAsync(
                    $"{_mockProviderServiceBaseUri}/api/v1/",
                    metadata,
                    myJsonObject,
                    CancellationToken.None);
            }
            catch (Exception)
            {
                // ignored
            }

            //Assert
            _mockProviderService.VerifyInteractions();`

It does not seem like a very elegant solution though but it works. Hopefully it helps someone.

**Comment by neilcampbell** [comment]
@bdelsaz Thanks for the extensive details! Yeah that use case is supported.

I'm thinking it might be related to nunit and parallelising the tests. Try moving `_mockProviderService.VerifyInteractions();` to the `[OneTimeTearDown]` method, which should verify all interactions after all the tests have been run. Also `_consumerPact.PactBuilder.Build();` should probably be `_consumerPact.Dispose()`

Also looking at your Gist I noticed that `consumer-provider.json` only contains 1 interaction. It should contain them all if the test setup is correct. My guess is that you might have just ran that single test when capturing the output? Just double check that when you run all tests, the pact file contains all the registered interactions.

**Comment by bdelsaz** [comment]
@neilcampbell thanks for your response!

I tried your suggestions and these are my conclussions:

Moving ```_mockProviderService.VerifyInteractions();``` to the ```[OneTimeTearDown]``` method - I get the same results. The log file show that 3 of the 4 tests did not match the interactions (the ones returning exceptions). However on my test results in VS all shows green. I don't like this because I don't get the real failing tests in the overview. The pact file ```consumer-provider.json``` still shows only 1 interaction, the one of the call returning the complete json file. 

I tried as well to wrap the setting up of the mock service inside the ```Func<Task> act => ....``` like this:

```            
            Func<Task> act = async () =>
            {
            //Arrange
            var metadata = new MetadataBuilder().Build();

            var myJsonObject = new AJsonObjectBuilder().Build();

            _mockProviderService.Given("IdentifyPersonRequest with 401 response")
                .UponReceiving("a request with empty machine ID header")
                .With(new ProviderServiceRequest
                {
                    Method = HttpVerb.Post,
                    Path = "/api/v1/person/identify",
                    Headers = new Dictionary<string, object>
                    {
                        {"Content-type", "application/json; charset=utf-8"},
                        {"X-Reference-Id", metadata.Session.SessionId},
                        {"X-Machine-Id",string.empty}
                    },
                    Body = myJsonObject
                })
                .WillRespondWith(new ProviderServiceResponse
                {
                    Status = 400,
                    Headers = new Dictionary<string, object>
                    {
                        {"Content-Type", "application/json; charset=utf-8"}
                    },
                    Body = new
                    {
                        type = "validation-failed",
                        title = "Validation failed",
                        status = 400,
                        detail = "null",
                        data = new
                        {
                            MachineId = "'Machine Id' must not be empty.",
                        }
                    }
                });

                //Act
                await _consumer.IdentifyAsync(
                    $"{_mockProviderServiceBaseUri}/api/v1/",
                    metadata,
                    myJsonObject,
                    CancellationToken.None);
            };

                //Assert
                _mockProviderService.VerifyInteractions();
```

But still get the same results on the log file and the pact file. 

> Also looking at your Gist I noticed that `consumer-provider.json` only contains 1 interaction. It should contain them all if the test setup is correct. My guess is that you might have just ran that single test when capturing the output?

Double-checked and this is not the case; I run all the tests and still only one interaction is registered.
So for now I'll stick to the try-catch solution as it seems to agree with the execution flow of NUnit.

Thanks again for the help! :)
