### ISSUE TITLE
Long url request always returns 200 status with empty response body. 

### ISSUE THREAD

**Issue by Morshed11218** [pact-foundation/pact-net#192]
For pact mock service, noticing that when a url character count is larger than 2,088, the response returns 200 status with empty results. Even if the request does not match the expected request, the response is always 200 status with empty body. 

example url:

http://localhost:782/v1/Users?criteria=%5B%7B%22field%22%3A%22id%22%2C%22operator%22%3A%22in%22%2C%22value%22%3A%5B%2201ea8292-1157-469d-a7eb-dbfff5ff0354%22%2C%220679bb8e-9063-4201-a536-0c46a644bfd5%22%2C%22091787d4-a64e-4606-aaa5-adea82b31680%22%2C%220da1e08e-6cba-4a6a-8d0b-531253abd20b%22%2C%220e0ea0fe-048d-4ffb-a15e-2805ccf68929%22%2C%2214d60d25-7b2a-437b-b921-4e118800da5c%22%2C%221510afbe-2a5c-4051-8194-affce4cdac4a%22%2C%221a712e99-9c37-407e-9461-3cbf3eb0da1c%22%2C%222a9467bb-4587-4bf5-987e-10151acaf9f2%22%2C%2230266159-744a-48c8-bed7-b26160ca923e%22%2C%2231b53eec-9015-4a8e-88a4-9b989cf973db%22%2C%2233262230-3243-4edc-aef5-67516cd60ab3%22%2C%223956c7a8-02e6-45ae-9d24-a4c238156e7c%22%2C%223e9a7623-518e-4fb1-a814-ac4d3f2d40d4%22%2C%224e9948a7-102f-4e1f-bb7f-1fc9e6cd2883%22%2C%224f6631b8-d788-4e6a-b19c-7e2a8ce6f3a4%22%2C%225953df34-3e74-480e-bcbc-1227d83e23a5%22%2C%225b302df9-3fad-4f2d-b769-f2bef3334d44%22%2C%225b7fe350-e517-4646-b29a-56d76308e633%22%2C%22600f0b83-9083-4476-9a0a-19ac7ff1bb40%22%2C%22624ba97d-eef2-4ab4-8f75-dd378b1bd8cb%22%2C%2262e3c2f3-49f5-4262-8963-b32873c4fd08%22%2C%22648ecd6f-2091-495b-9f8e-50e55412dbe9%22%2C%226c670dc6-9a58-4b91-89c9-b73a8d859da1%22%2C%2271aa210d-6fd3-44d5-bbcb-4258db25cfb8%22%2C%22738045bb-81f5-45c2-aeb9-4e1cff8c7965%22%2C%227471608f-b09a-46f9-9162-44c0aa5b307b%22%2C%227c989116-0b03-4fbf-9986-7b1e0e082958%22%2C%2286210df5-b183-4e9e-adbe-6216325e819b%22%2C%2286bbfa02-07d6-4164-b3db-534456206eee%22%2C%229387abaf-3a45-475a-a9c7-599c8e22a335%22%2C%2293bff86b-f0b1-4dd3-9fa8-f6d9362333f2%22%2C%22a5353df0-d23c-451a-a61b-8a35620c65b4%22%2C%22a7f754a9-f051-48c1-a0ec-3dd2188e6f5b%22%2C%22aa624095-9357-4030-a07e-39c454050a27%22%2C%22b4e39487-13da-409e-9c7a-f03e691f8e7b%22%2C%22b744bf05-d18d-4769-be4d-8029efd58b87%22%2C%22b9788592-f63f-4790-8318-912d874682f5%22%2C%22bbe3e5a8-37bc-4774-b540-95cfb700ab66%22%2C%22c15e2520-9441-44fe-8156-2798db06747d%22%2C%22c886c107-40ab-4ba8-9b92-2fe697068bb1%22%2C%22cc786b01-2a63-4ed3-87c4-dbdd44dec5d8%22%2C%22e0553e3-1fdb22-42-5f698f28b%22%2C%22f2703081%22%5D%2C%22aggregate%22%3Anull%7D%5D

**Comment by neilcampbell** [comment]
Hi @Morshed11218. Unfortunately that is actually quite a common limitation in browsers and http clients for example Chrome has a 2083 character limit. It's likely something strange happening in the  ruby mock provider. I'd recommend adjusting the API design to fit, otherwise you might find yourself running into issues when real clients try to connect as well.

**Comment by bethesque** [comment]
A common work around for the use case where a query is exceptionally long is to use a post with body parameters instead. Perhaps this would work for you @Morshed11218
