### ISSUE TITLE
Verify pactUri with array of tags

### ISSUE THREAD

**Issue by namhuynhkien** [pact-foundation/pact-net#201]
Currently it's only able to very single tag (i.e. master or latest tags) as below.
`new PactVerifier(config)
   .ProviderState($"{PactServiceUri}/provider-states")        
   .ServiceProvider(ProviderName, ProviderUri)
   .HonoursPactWith(ConsumerName)
.PactUri($"PactUtilities.PactBrokerCloud}/pacts/provider/{ProviderName}/consumer/{ConsumerName}/master").Verify();`
It would be great if we can pass multiple tags without iterating the above script.

**Comment by neilcampbell** [comment]
I'd usually just have two provider verifications test for each of those tags. Happy to support multiples though. Probably the easiest way is to add support for multiple pact uris, so in essence adding a `.PactUris()` method. Are you interested in doing a PR for this?

**Comment by namhuynhkien** [comment]
Hi Neil, 
I'm happy to do it in my spare time. I have another idea that passing a string with separator such as ' ' (space) character. What do you think about?

**Comment by neilcampbell** [comment]
I think the space separated idea doesn't make it explicit enough. Personally I much prefer having a new method.

**Comment by namhuynhkien** [comment]
I'd like to explain more about my idea.
```
new PactVerifier(config) .ProviderState($"{PactServiceUri}/provider-states") .ServiceProvider(ProviderName, ProviderUri) .HonoursPactWith(ConsumerName) .PactBroker($"PactUtilities.PactBrokerCloud}
.Tags("master production").Verify();
```
We can separate the PactURL with the tags. The Tags function can receive a string with space separators. I would like to get this because I want it to be an environment variable. So that our CICD script can determine which tags should be verify in the provider test. That benefits us from modify the provider test. Otherwise, I would love to hear if you have any other idea that can achieve this. (or maybe I'm the only one who want to do this 🤣 )

**Comment by neilcampbell** [comment]
> We can separate the PactURL with the tags
Sorry I don't understand what you mean?

> The Tags function can receive a string with space separators
`IEnumerable<string>` makes it a more friendly and discoverable api. If you support a space why wouldn't you also support a `,` and `|` etc, it becomes a more complex implementation which also needs to be documented.

If you retrieve the value from an environment variable, it shouldn't be too much hassle to add some code prior to instantiating the PactVerifier which splits the string into a List<string>.

Things to think about here are backwards compatibility, I don't really want to break it unless there is a really good reason to. How does your suggestion work with verification of a pact file locally?

**Comment by namhuynhkien** [comment]
> How does your suggestion work with verification of a pact file locally?

this one beats me. we cannot verify pact file locally.
Hmmm I guess we create another constructor that accept `IEnumerable<string> ` is good enough though.

**Comment by neilcampbell** [comment]
I don't think you'd do it in a constructor.

I was thinking to add a new method `PactUris(IEnumerable<string> uris)`.
That way you can support either broker urls or local urls, and it's all backwards compatible.

It does mean that for your use case, you'd need to split the environment variable, and map that into a broker uri, which I think should be fairly manageable. Thoughts?

**Comment by neilcampbell** [comment]
Something like https://gist.github.com/neilcampbell/611117098a73c42e59b36737182de919
Using `Environment.GetEnvironmentVariable("PACT_TAGS");`

**Comment by namhuynhkien** [comment]
> I don't think you'd do it in a constructor.

By bad, I mean that creates an overload function of PactUri. 

> I was thinking to add a new method `PactUris(IEnumerable<string> uris)`.

Yes, it will both support

> It does mean that for your use case, you'd need to split the environment variable, and map that into a broker uri, which I think should be fairly manageable. Thoughts?

Yes, it's manageable. I'll start working on that when as soon as I can. Thanks Neil.

**Comment by adamrodger** [comment]
v4.0 will support multiple tags
