### ISSUE TITLE
Using Pact for Windows, Mock server not returning response object with content.

### ISSUE THREAD

**Issue by charlescboucher** [pact-foundation/pact-net#202]
Hi,

We are using the mockserver for testing and have noticed that the response object we setup in our tests does not return any value.

see:  _mockProviderService
                .Given("There is an Experian Payload")
                .UponReceiving("A valid POST request for Address Validation with valid payload")
                .With(new ProviderServiceRequest
                {
                    Method = HttpVerb.Post,
                    Path = "/experian/defaultrequestlistener"
                })
                .WillRespondWith(new ProviderServiceResponse
                {
                    Status = 200,
                    Headers = new Dictionary<string, object>
                    {
                        {"Content-Type", "application/json; charset=utf-8"}
                    },
                    Body = new
                    {
                         message=E2ETestFixtures.GetExperienceResponse()
                    }
                });

E2ETestFixtures.GetExperienceResponse() is a json file.

When we call the enpoint we do get a 200 as expected but the response object is not returned.

Can this be done?

Thanks,

Charles

**Comment by neilcampbell** [comment]
What type is returned by `E2ETestFixtures.GetExperienceResponse()`?

**Comment by charlescboucher** [comment]
I was passing json as a string.  I have discovered that the body requires a c# object.

Thanks charles

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
