### ISSUE TITLE
Body in ProviderServiceRequest is array or object with inner object

### ISSUE THREAD

**Issue by thangtnguyen** [pact-foundation/pact-net#205]
Hello,

I am facing with the issue. When I use Body is an array in ProviderServiceResponse with POST request as the below code I received the test is fail when I run the consumer as the screen shot
var testBody = new[]
            {
                new {
                    id = Match.Type("Id"),
                    topic = "customers-egrid-datachangenotification-topic-dev1",
                    eventType = "Microsoft.EventGrid.SubscriptionValidationEvent",
                    subject = Match.Type("Subject"),
                    dataVersion = "Major version",
                    metaDataVersion = "MetaDataVersion",
                    eventTime = Match.Type(DateTime.Now),
                    data = new
                    {
                        validationCode = Match.Type("ValidationCode"),
                        validationUrl = Match.Type("ValidationUrl")
                    }
                },
                new {
                    id = Match.Type("Id"),
                    topic = "customers-egrid-datachangenotification-topic-dev1",
                    eventType = "Microsoft.EventGrid.SubscriptionValidationEvent",
                    subject = Match.Type("Subject"),
                    dataVersion = "Major version",
                    metaDataVersion = "MetaDataVersion",
                    eventTime = Match.Type(DateTime.Now),
                    data = new
                    {
                        validationCode = Match.Type("ValidationCode"),
                        validationUrl = Match.Type("ValidationUrl")
                    }
                }
            };

 _mockProviderService.Given($"There is a customer list3")
                .UponReceiving($"A request with Subscription Validation Event which has Invalid Topic")
                .With(new ProviderServiceRequest
                {
                    Method = HttpVerb.Post,
                    Path = $"/customers/datachanged",
                    Headers = new Dictionary<string, object>
                    {
                        { "Content-Type", "application/json"}
                    },
                    Body = testBody
                })
                .WillRespondWith(new ProviderServiceResponse
                {
                    Headers = new Dictionary<string, object>
                    {
                        {"Content-Type", Match.Regex("application/json; charset=utf-8", "json") }
                    },
                    Status = 400,
                    Body = new
                    {
                        title = Match.Type("is not supported")
                    }
                });

![image](https://user-images.githubusercontent.com/8353828/63849063-66aa1280-c9bb-11e9-9ccd-fa3c406f508c.png)

Is there any thing incorrect? Please help.

Thanks,
Thang

**Comment by neilcampbell** [comment]
The error indicates there is already something listing on the port you are trying to run the Pact mock service on. Try killing all ruby processes or restarting your computer.

I'd also recommend starting with a more simple example and building the test up from there.

**Comment by thangtnguyen** [comment]
Hi @neilcampbell ,

Thanks for your response. I restarted my machine and try to run. Another error happened. Please see the screenshot

Thang
![image](https://user-images.githubusercontent.com/8353828/63904211-67ce5480-ca3a-11e9-90a4-43c8805525e1.png)

**Comment by thangtnguyen** [comment]
Hi @neilcampbell ,

I extract the code for simple case with an inner object and error happens. I have tried with flat object, it works.

Test method:
public async Task SimpleTest()
        {
            var testbody = new
            {
                id = Match.Type("Id"),
                topic = "customers-egrid-datachangenotification-topic-dev1",
                eventType = "Microsoft.EventGrid.SubscriptionValidationEvent",
                subject = Match.Type("Subject"),
                dataVersion = "Major version",
                metaDataVersion = "MetaDataVersion",
                eventTime = Match.Type(DateTime.Now),
                data = new
                {
                    validationCode = Match.Type("ValidationCode"),
                    validationUrl = Match.Type("ValidationUrl")
                }
            };

            _mockProviderService.Given("Simple Test")
                .UponReceiving($"Receiving")
                .With(new ProviderServiceRequest
                {
                    Method = HttpVerb.Post,
                    Path = $"/customers/datachanged",
                    Headers = new Dictionary<string, object>
                    {
                        { "Content-Type", "application/json"}
                    },
                    Body = testbody
                })
                .WillRespondWith(new ProviderServiceResponse
                {
                    Headers = new Dictionary<string, object>
                    {
                        {"Content-Type", Match.Regex("application/json; charset=utf-8", "json") }
                    },
                    Status = 400,
                    Body = new
                    {
                        title = Match.Type("is not supported")
                    }
                });

            //Action
            var consumer = new ApiClient(_mockProviderServiceBaseUri);
            var response = await consumer.PostSimpleCase();

            //Assert
            Assert.IsTrue(response.StatusCode == HttpStatusCode.BadRequest);
            _mockProviderService.VerifyInteractions();
        }

The code for ApiClient
public async Task<HttpResponseMessage> PostSimpleCase()
        {
            HttpContent content;

            var payload = new List<EventGridEvent>();
            var data = new SubscriptionValidationEventData("abc", string.Empty);
            var eventGrid = new EventGridEvent("Event Id", "Company", data,
                "Microsoft.EventGrid.SubscriptionValidationEvent", new DateTime(), "Major Version", "topic",
                "MetaDataVersion");
           // payload.Add(eventGrid);
            var strPayload = JsonConvert.SerializeObject(eventGrid);
            content = new StringContent(strPayload, Encoding.UTF8, "application/json");
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");

            using (var response = await _client.PostAsync($"customers/datachanged", content))
            {
                return response;
            }
        }

If I miss anything or make any mistake, please let me know. 

Thanks
Thang

**Comment by neilcampbell** [comment]
Does the `strPayload` match exactly (including case) to the testbody?
With seeing exactly what strPayload is, I can't really help. What status code are you getting back? Have you checked the log file that pact generates?

**Comment by thangtnguyen** [comment]
Hi @neilcampbell ,

Thanks for your above guides. Finally, I managed to modify the code after review the logs and it works as expected now.

Thang

**Comment by cetk** [comment]
Hi, can you please share your findings? I have same problem , flat object with string values works, but request body object with inner objects gives error as no interaction found , I have all properties of inner object along with values matches.
