### ISSUE TITLE
Multiple custom headers in PactVerifierConfig

### ISSUE THREAD

**Issue by scalancea** [pact-foundation/pact-net#209]
In our project we need several custom headers for authorization on API. They also need to be dynamically generated. In my fork I was able to successfully change the `PactVerifierConfig` to accept a dictionary of custom headers.

Questions:
- Was the one custom header limit imposed on purpose? Was there any limitation imposed by ruby under the hood or windows shell?
- Would such a feature be useful for anyone? Should I merge it back here?

Usage example;
```csharp
var config = new PactVerifierConfig
{
    Outputters = new List<IOutput>
    {
        new XUnitOutput(_output)
    },
    CustomHeaders = new Dictionary<string, string>
    {
        // any headers you wish
        { "x-my-appname", "pactIO" },
        { "x-my-appauth", authHeader }
    }
};

//Act / Assert
IPactVerifier pactVerifier = new PactVerifier(config);
    pactVerifier
        .ServiceProvider("Event API", serviceUri)
        .HonoursPactWith("Event API Consumer")
        .PactUri(pactUri)
        .Verify();
```

**Comment by neilcampbell** [comment]
It was my understand that the ruby core only accepted a single header key value pair, however I could be wrong. Did you manage to get it working with multiple headers?

**Comment by scalancea** [comment]
Yes [it is actually possible](https://github.com/pact-foundation/pact-python/blob/cf5d5bcd64f0537adf9ac187b23b64944f1a2043/pact/verify.py#L54-L60). 
Here is an excerpt of my code (it is not pushed yet, though)
```csharp
foreach (var header in config.CustomHeaders.Where(kv => !string.IsNullOrEmpty(kv.Key) && !string.IsNullOrEmpty(kv.Value)))
{
    builder.Append($" --custom-provider-header \"{header.Key}:{header.Value}\"");
}
```

**Comment by neilcampbell** [comment]
Nice. Yeah that would be awesome if you could send a PR for it!
