### ISSUE TITLE
Question: How to generate different values in body using Match.Mintype 

### ISSUE THREAD

**Issue by TheBsal** [pact-foundation/pact-net#211]
Is it possible to generate different values on the my collection for pact
Response body looks like this 
Body = Match.MinType(new
                    {
                        Property1= Match.Type("Name"),
                        Property2= Match.MinType(new
                        {
                            subprop1= Match.Type(true),
                            subprop2= Match.Type("City"),
                            subprop3= Match.Type("Country")
                        }, 1),
                    }, 50)

I want to define the property value for my first 3 in the collection ?

**Comment by neilcampbell** [comment]
@TheBsal You can only add data for a single item. By using the matchers you are essentially saying that the specific values are not important, it's the structure and the types that are.

**Comment by TheBsal** [comment]
Thanks for your response.
