### ISSUE TITLE
Question- How can i manage test across multiple files

### ISSUE THREAD

**Issue by TheBsal** [pact-foundation/pact-net#212]
Hello, i have pact-net test across multiple files.  After test run is completed it seems like pact.json is overwritten by last test that was ran.  Is there's a way for me to have this configured from override to update. This test is for same consumer and provider.

**Comment by neilcampbell** [comment]
I should update by default. My guess is that you are instantiating `PactBuilder` or the `MockService` more than once, those should be shared between all test in a Pact.

**Comment by TheBsal** [comment]
@neilcampbell  thanks for your response. I changed from IClassFixture to ICollectionFixture and issue got resolved.
