### ISSUE TITLE
How to write a matching rule when you the property can bring back value or null . This property is string type

### ISSUE THREAD

**Issue by startedtocode** [pact-foundation/pact-net#213]
If someone can help me out here,

i am trying to write a body with the matching type

name = Match.Type("name")
name = Match.Regex("name", "^name")

i tried both approaches but on the provider side test fails. Reason is some of the name prop in provider response collection has null value and some has value.

basically actual value could be name = null or name = john

**Comment by neilcampbell** [comment]
Hi @startedtocode,
`Match.Type` will check the value is of the type specific (string in this case). Null is not a string, so it won't match. `Match.Regex` will check the value matches that expression, which also won't match as it's not the string "name".

In your case it sounds like your consumer actually doesn't care if the value for name is null or set to a value, so you could just omit it entirely from the contract.

If you do in fact want to check this you'll need to be able to control the data returned from the provider using provider states and some custom code on the provider side.

**Comment by startedtocode** [comment]
Thanks for your reply @neilcampbell .

For me , field "name" is very important. As this filed is consumed and processed based on the value ( which is null or string). So i believe, my contract should be something like 

1. the property name = > "name" should always be returned
2. It could be type of string or null.

if i don't have this field in my contract json , then if my provider removes this field, the provider side test will pass but actual interaction will fail. 

I believe this kind of cases are very normal in api's. Please suggest.

**Comment by neilcampbell** [comment]
When the name field is set to null, what does the consumer code do? What does it do when it's set to a value?

**Comment by tomhoangle** [comment]
I am also running into the same problem. I would like to have it match type "string" or null.
For my task, if the value is null, the consumer will output null field to their UI.

The other way is to create pact test for each time variables are null which will create nightmare code to maintain.

**Comment by KristinaCtr** [comment]
I am having the same issue as well.  This issue is very common if you are dealing with data returning from a database table.  Data can be NULL for any datatype, i.e. integer, float, string, datetime, etc. Consumer would check for NULL data and it is up to consumer to decide what to display on the UI screen for NULL.  Most likely, consumer would display blank for NULL, otherwise displays whatever data return back from provider.  The Match.Type needs to support checking "String or NULL", "Integer or NULL", "Float or NULL", "DateTime or NULL", etc.

**Comment by startedtocode** [comment]
@neilcampbell - Apologies for late reply, i was out of office. On Consumer side if the value of that property is null it will invoke function which calls another endpoint. If it has value then it won't. Seems like this is common use cases. I agree with @KristinaCtr  point that Match.Type should have overload to match multiple types.

**Comment by neilcampbell** [comment]
@startedtocode It sounds like that is an explicit case then that should be tested. So have a test for when the value is explicitly null and check that it perform that additional call. Also have a test for when that value is set to a string value and ensure that the additional call isn't made.

**Comment by KristinaCtr** [comment]
**@neilcampbell** - matchingRules for "NULL or <Type>" was added in pact-jvm version 3.  Please see **https://github.com/DiUS/pact-jvm/issues/261** for detail.  Can we have this feature added for pact-net?  The MatchingRules for "String or NULL", "Integer or NULL", "Float or NULL".

**Comment by neilcampbell** [comment]
@KristinaCtr Unfortunately I can't as it's supported in the ruby standalone core that we use. The only thing really you can do is setup the data to return NULL deterministically and not use a matcher for that scenario.

**Comment by startedtocode** [comment]
@neilcampbell . I believe setting data for these sort of cases in the provider side is kind of overhead. One provider can have many consumers and i don't expect them to support these sort of use cases for all. Also, i believe it is consumer responsibility to provider appropriate matching rules for all the use cases for them.

**Comment by neilcampbell** [comment]
@startedtocode Yeah agreed there is an overhead, however if you want test that are deterministic, control of data is super important and worth investing in. In my eyes having matchers doesn't completely negate the need for being able to control the data that a provider returns under certain scenarios.

**Comment by bethesque** [comment]
@startedtocode have you read this? https://docs.pact.io/faq#why-is-there-no-support-for-specifying-optional-attributes
