### ISSUE TITLE
Question- Passing auth token from provider side

### ISSUE THREAD

**Issue by startedtocode** [pact-foundation/pact-net#214]
Hello, is there's an example on how to send auth token on provider side to validate the pact file ?

I have my consumer side pact written. My pact file doesn't have any headers with auth and token. 

In provider side for me to make an actual api call, i need to provide token.  
 "ServiceProvider(ProviderName, ServiceUrl)" -- Service provide only lets you to send baseurl as string.  I am not quiet sure on how to send token to make an actual call. Please share me if you have a solution or documentation.

**Comment by neilcampbell** [comment]
Hi @startedtocode 
You have a few options here. You can use `CustomHeaders` on `PactVerifierConfig` and supply an Authorization header there (search for "Authorization" in the README for the syntax) or you could do something like what is done in the samples https://github.com/pact-foundation/pact-net/blob/master/Samples/EventApi/Consumer.Tests/EventsApiConsumerTests.cs#L106 and then https://github.com/pact-foundation/pact-net/blob/master/Samples/EventApi/Provider.Api.Web.Tests/AuthorizationTokenReplacementMiddleware.cs#L25, which uses a test middleware that is injected when you spin up your provider at verification time and replaces the known sample token with valid one.

**Comment by startedtocode** [comment]
Thanks @neilcampbell . This worked out for me.
