### ISSUE TITLE
.NET Implementation of requestFilter seen on JS and GO version of Pact.

### ISSUE THREAD

**Issue by mmysliwiec** [pact-foundation/pact-net#216]
I've read nice article about dealing with dynamically generated authentication: https://medium.com/dazn-tech/pact-contract-testing-dealing-with-authentication-on-the-provider-51fd46fdaa78

I have exactly the same problem. The article mentions about `requestFilter` solution which would be perfect for me. I can see the `requestFilter` is implemented only in JS and GO versions of Pact. Are you planning to implement this in .NET as well? It would be very helpful for dynamic authentication. Is there any other way to generate authentication header based on given request URL (per interaction rather than one header per contract file).

**Comment by akbhartiya** [comment]
you can your dynamically generated auth token to request as below
public async Task TestMyService()
        {
            var token = GetDynamicToken(); // get/genereate you dynamic token here.
            var pactConfig = new PactVerifierConfig
            {
                Outputters = new List<IOutput> {
                    new XUnitOutputter(_output)
                },
                Verbose = true,
                CustomHeader = new KeyValuePair<string, string>("Authorization", $"Bearer {token}")
            };

            new PactVerifier(pactConfig)
                .ServiceProvider(providerName: "Provider", serviceUri)
                .HonoursPactWith("Consumer")
                .PactUri("Path to you contract file")
                .Verify();
        }

**Comment by mmysliwiec** [comment]
Yes, I know. The problem is our authentication token is based on the request URL and it's different for each interaction so we can't generate it once.

**Comment by neilcampbell** [comment]
Another option is to inject some middleware in your provider when you start it for verification. See https://github.com/pact-foundation/pact-net/issues/214

**Comment by neilcampbell** [comment]
To answer your original question, no we currently don't have any plans to implement that feature. We are happy to discuss and accept PR's though 😄

**Comment by adamrodger** [comment]
Closed due to inactivity
