### ISSUE TITLE
How to match array items in different order. 

### ISSUE THREAD

**Issue by Morshed11218** [pact-foundation/pact-net#217]
Hi,
How can I make it so that when it comes to contract verification, I want to ignore the ordering of the arrays. 

Example: 

{
	"names": [
		"John",
		"Jim",
		"Tim"
	]
}

I want it to match this response with the names in different order 

For example:
{
	"names": [
		"Tim",
		"John",
		"Jim"
	]
} .. or any other combination.

**Comment by neilcampbell** [comment]
So is the data important or do you just want to validate that it's a non empty array? If so you can use `Match.MinType("Janet", 3)`. 3 is the minimum number of items you expect.

**Comment by Morshed11218** [comment]
> So is the data important or do you just want to validate that it's a non empty array of strings? If so you can use `Match.MinType("Janet", 3)`. 3 is the minimum number of items you expect.

data matters for me. Is there a way I can verify the data without having to match the order?

**Comment by neilcampbell** [comment]
Not on the pact side, ideally your test data on the provider side should be deterministic, so you should just be able to match the order on the consumer side.
