### ISSUE TITLE
Best approach for keeping your contract data away from test method when generating contract file?

### ISSUE THREAD

**Issue by akbhartiya** [pact-foundation/pact-net#219]
Hi Team,
can you please suggest me the best way to keep test data (request and response) separated from Test method. eg.  I do not want to mix both of these at same place while generating contract file. for below test method what could be best place to put test data rather than combining it at same place.

If i am trying to keep my test data in separate json file i am unable to use regular expression with some dynamic type data. eg i want to apply regular expression on timestamp field. 
[Fact]
        public void GetAllEvents_WhenCalled_ReturnsAllEvents()
        {
            var test = new[]
            {
                new
                {
                    eventId = Guid.Parse("45D80D13-D5A2-48D7-8353-CBB4C0EAABF5"),
                    timestamp = "2014-06-30T01:37:41.0660548",
                    eventType = "SearchView"
                },
                new
                {
                    eventId = Guid.Parse("83F9262F-28F1-4703-AB1A-8CFD9E8249C9"),
                    timestamp = "2014-06-30T01:37:52.2618864",
                    eventType = "DetailsView"
                },
                new
                {
                    eventId = Guid.Parse("3E83A96B-2A0C-49B1-9959-26DF23F83AEB"),
                    timestamp = "2014-06-30T01:38:00.8518952",
                    eventType = "SearchView"
                }
            };

            var res = new ProviderServiceResponse
            {
                Status = 200,
                Headers = new Dictionary<string, object>
                {
                    {"Content-Type", "application/json; charset=utf-8"}
                },
                Body = test
            };

            //Arrange
            var testAuthToken = "SomeValidAuthToken";

            _mockProviderService.Given("there are events with ids '45D80D13-D5A2-48D7-8353-CBB4C0EAABF5', '83F9262F-28F1-4703-AB1A-8CFD9E8249C9' and '3E83A96B-2A0C-49B1-9959-26DF23F83AEB'")
                .UponReceiving("a request to retrieve all events")
                .With(new ProviderServiceRequest
                {
                    Method = HttpVerb.Get,
                    Path = "/events",
                    Headers = new Dictionary<string, object>
                    {
                        { "Accept", "application/json" },
                        { "Authorization", $"Bearer {testAuthToken}" }
                    }
                })
                .WillRespondWith(res);

            var consumer = new EventsApiClient(_mockProviderServiceBaseUri, testAuthToken);

            //Act
            var events = consumer.GetAllEvents();

            //Assert
            Assert.NotEmpty(events);
            Assert.Equal(3, events.Count());

            _mockProviderService.VerifyInteractions();
        }

**Comment by neilcampbell** [comment]
That side of things is really up to you. You could use a json file, then deserialise into a .NET object, with on of the fields in the .NET object being of type `RegexMatcher`. You just need to make sure the json field is serialised correctly, so that it deserialised correctly. Alternatively you could create an Object mother https://martinfowler.com/bliki/ObjectMother.html with the pre canned test data and not use a json file at all.
