### ISSUE TITLE
NuGet Package Links A Lot of Superfluous Content

### ISSUE THREAD

**Issue by Silvenga** [pact-foundation/pact-net#220]
The nuge package introduces a lot of superfluous content into the solution, so if, for example, a developer uses Resharper with the default settings, they will see CSS syntax errors from documentation found in the Ruby gems.

![image](https://user-images.githubusercontent.com/2753330/67702728-44634f80-f980-11e9-97b1-9503dc2b8ccb.png)

This has an impact on the "less than native" experience when working with the .Net pact library when compared to the Java implementation.

**Comment by neilcampbell** [comment]
@bethesque Do you know of any reason that this might cause issues with the standalone core? Seems like it should be a pretty safe change.

**Comment by bethesque** [comment]
Sorry, I missed this issue @neilcampbell. So many notifications. I'm removing those files from the pact-ruby-standalone.
