### ISSUE TITLE
PactNet.Linux.x64 issue with docker

### ISSUE THREAD

**Issue by bogdbo** [pact-foundation/pact-net#228]
Hey,

I'm trying to setup a very basic test project and I got most things working on windows but when building and running the same code on linux with docker, I keep getting a few errors that I don't get on windows.

This is the whole project configuration
`<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>netcoreapp3.0</TargetFramework>
        <RootNamespace>Platform.Microservice.Api.ContractTests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="2.0.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="2.0.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.2.0" />
        <PackageReference Include="PactNet.Linux.x64" Version="2.4.8" />
        <PackageReference Include="PactNet.Windows" Version="2.4.8" />
        <PackageReference Include="xunit" Version="2.4.0" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
    </ItemGroup>

</Project>`

The docker image is `mcr.microsoft.com/dotnet/core/sdk:3.0`

The test

```
        [Fact]
        public void EnsureProviderApiHonoursPactWithConsumer()
        {
            // arrange
            var config = new PactVerifierConfig
            {
                Outputters = new[] {new XUnitOutput(outputHelper)},
                Verbose = true,
                PublishVerificationResults = true,
                ProviderVersion = "1.0.0",
            };
            // act & assert
            var verifier = new PactVerifier(config);
            verifier.ProviderState($"{pactServiceUri}/provider-states")
                .ServiceProvider("provider", providerUri)
                .HonoursPactWith("consumer")
                .PactUri("http://<redacted>/pacts/provider/microserviceApi/consumer/microserviceApiConsumer/latest")
                .Verify();
        }
```

Issue 1:
If `providerUri` is specified as `http://provider:5000` I get the following error:
```
contract_tests_1  | [xUnit.net 00:00:00.76]     Platform.Microservice.Api.ContractTests.UnitTest1.EnsureProviderApiHonoursPactWithConsumer [FAIL]
contract_tests_1  |   X Platform.Microservice.Api.ContractTests.UnitTest1.EnsureProviderApiHonoursPactWithConsumer [196ms]
contract_tests_1  |   Error Message:
contract_tests_1  |    System.UriFormatException : Invalid URI: Invalid port specified.
contract_tests_1  |   Stack Trace:
contract_tests_1  |      at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
contract_tests_1  |    at System.Uri..ctor(String uriString)
contract_tests_1  |    at PactNet.PactVerifier.ServiceProvider(String providerName, String baseUri)
contract_tests_1  |    at Platform.Microservice.Api.ContractTests.UnitTest1.EnsureProviderApiHonoursPactWithConsumer() in /microservice-template/test/a/UnitTest1.cs:line 46
```
If I add a trailing slash to the `providerUri` (`http://provider:5000/`), the error goes away but then something else fails

Issue 2:
What runs and publishes the results correclty on windows, throws the following error on linux

```
contract_tests_1  |        Failure/Error: replay_interaction interaction, options[:request_customizer]
contract_tests_1  |
contract_tests_1  |        URI::InvalidURIError:
contract_tests_1  |          bad URI(is not URI?): http://provider:5000/ --provider-states-setup-url http://127.0.0.1:5001/provider-states --publish-verification-results=true --provider-app-version=1.0.0 --verbose true/api/microservice/store
```
When debuging (form windows) how the `ProcessStartInfo` is configured, this is the value of `processStartInfo.Arguments`

`-rbundler/setup -I"C:\p\p\services\microservice-template\test\a\bin\Debug\netcoreapp3.0\\pact-win32\lib\app\lib" "C:\p\p\services\microservice-template\test\a\bin\Debug\netcoreapp3.0\\pact-win32\lib\app\pact-provider-verifier.rb" "http://<redacted>/pacts/provider/microserviceApi/consumer/microserviceApiConsumer/latest" --provider-base-url http://localhost:5000 --provider-states-setup-url http://127.0.0.1:5001/provider-states --publish-verification-results=true --provider-app-version="1.0.0" --verbose true`

^ the above works without any issues on windows, even the missing slash at the end of the `providerUri`.

**Comment by neilcampbell** [comment]
Does issue 2 go away when you remove the trailing `/`?

**Comment by bogdbo** [comment]
If I remove the `/` I get issue 1, I'm not sure it even reaches the part where issue 2 normally happens. I have switched in the meantime to the CLI docker image `pactfoundation/pact-cli:latest` to validate the pacts. Works fairly niceley and I only have to configure the `provider-states-setup-url` which, for now, I plan to keep it in the main app. I'm only mentioning it, in case someone else has trouble and needs an quick solution.

**Comment by neilcampbell** [comment]
Yeah without a sample to reproduce locally, I can't really do much more. It's a weird error, I'm not sure why they aren't considered valid uris.
