### ISSUE TITLE
Pact JSON file not being created when running into a Docker Container

### ISSUE THREAD

**Issue by david-tigerspike** [pact-foundation/pact-net#236]
Hello everyone, 

I'm currently trying to integrate my Pact Tests with a CI/CD pipeline. I have a .NET Core application that runs its tests and builds within a Docker container. 

I am able to run my tests on the machine I use to develop with no issues. Sadly, when the tests run within the container, the Pact file is not generated. On the other hand, it generates the pact log file and it does not contain any errors. 

Generated log file:
`
I, [2020-03-09T05:25:23.064685 #517]  INFO -- : Cleared interactions for example ""
I, [2020-03-09T05:25:23.271031 #517]  INFO -- : Registered expected interaction GET /api/People?query=...
D, [2020-03-09T05:25:23.271482 #517] DEBUG -- : {
  ...
}
I, [2020-03-09T05:25:24.821328 #517]  INFO -- : Cleared interactions for example ""
I, [2020-03-09T05:25:24.829914 #517]  INFO -- : Registered expected interaction GET /api/People?query=...
D, [2020-03-09T05:25:24.830098 #517] DEBUG -- : {
   ...
}
I, [2020-03-09T05:25:25.063320 #517]  INFO -- : Cleared interactions for example ""
`
Note that it is missing the message "Writing pact for *** to ***.json"

Here is the line that run the tests within the dockerfile
`dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:CoverletOutput=/testresults/coverage/"$i".xml "./tests/$prj"`

Thanks in advance for your help

Cheers

David

**Comment by bethesque** [comment]
I can't think of any reason immediately why this should be the case. Is it possible that the container is being shut down before the pact is being written?

**Comment by david-tigerspike** [comment]
Thanks heaps for your quick reply @bethesque

I have thought about that but the container keeps running for a while after the test step is finished. Also when I compare the log file generated on my machine with the one generated in the container, both of them end with the same line "Cleared interactions for example ''". However, the one that is generated on my machine says "Writing pact for *** to ***.json" right before while the one in the container does not... 

I have been digging in for a while and I have ruled out a permissions issue (pact it is able to run create the log file). I also have ruled out that the file is being created somewhere I do not expect (have tried to find anything that contains *pact* within the container).

**Comment by neilcampbell** [comment]
@david-tigerspike It's the `PactBuilder.Build()` method that writes the file. Maybe try running a single test and putting that inside the test method to see if it still doesn't write the pact file. My guess is that for some reason the test suite finalise/dispose isn't happening inside the container.

**Comment by david-tigerspike** [comment]
@neilcampbell Thanks for your time. Really appreciated it

I have already tried your approach with no success... I added the Pactbuilder.Build() at the end of a scenario and it did not work. Also I tried keeping it in both places (end of the scenario and the dispose method - where it currently lives) and the execution 'exploded' because the Build() method got called twice... 

This is a bit of a "poltergeist"... I'll keep digging but any ideas are welcome

**Comment by bethesque** [comment]
You could try hacking it by sending a POST to the mock service `http://localhost:<port>/pact` at the end of your test to force it to write the file. It wouldn't fix the underlying problem, but it might help identify something.

**Comment by neilcampbell** [comment]
@bethesque Good idea! @david-tigerspike Maybe it's a file system permission issue or something like that? I would have thought that the logs would show some kind of error if that was the case though.

**Comment by david-tigerspike** [comment]
Hello guys! 

Thanks for all the help. It ended up being a mix of a few issues on my side (misconfigured application together with odd failure handling on the pipeline) 

However, now it has been fixed and it is all running as expected. 

Thanks for all your time and sorry for the mess.

**Comment by neilcampbell** [comment]
@david-tigerspike Thanks for the update, glad you got it all sorted!
