### ISSUE TITLE
Please update Powershell gist to use TLS1.2

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-net#244]
Hi @neilcampbell, sorry to specify this to you, but you currently link to https://gist.github.com/neilcampbell/bc1fb7d409425894ece0 in your readme regarding publishing using Powershell. 

TL;DR - by default, PowerShell (or Windows more likely) defaults to SSL3/TLS1.0 :hurtrealbad:  which is bad. 

I've popped a comment on there, it would be great if you could update the Gist to include how to make it use modern TLS versions.

**Comment by neilcampbell** [comment]
Gist has been updated

**Comment by mefellows** [comment]
Awesome, thanks Neil!
