### ISSUE TITLE
Pact wip (working in progress) feature

### ISSUE THREAD

**Issue by tawfiknouri** [pact-foundation/pact-net#247]
Hello pact Team
It seems the pact wip not yet implemented for. Net library
Could you please implement this feature for. Net?
It's very nice feature!

Thank you very much

**Comment by bethesque** [comment]
The master issue for WIP pacts is here https://github.com/pact-foundation/pact_broker/issues/338

**Comment by neilcampbell** [comment]
@tawfiknouri Would you be interested in sending a PR to add this option?

**Comment by tawfiknouri** [comment]
@neilcampbell 
yes!, i will send a PR

**Comment by tawfiknouri** [comment]
@neilcampbell 
@bethesque 

https://github.com/pact-foundation/pact-net/pull/249
Tests & CI OK
Have a nice day
