### ISSUE TITLE
Add support provider tag for PactUri method

### ISSUE THREAD

**Issue by tawfiknouri** [pact-foundation/pact-net#248]
Hello Pact Team,
It seems we cannot tag provider using **PactUri** method

**pactVerifier.PactUri(changedPactUrl, pactUriOptions).Verify();** 

For builds triggered by a contract changed webhook, we need tag the provider with branch name, this option is possible only with **pactVerifier.PactBroker** 

Thanks

**Comment by bethesque** [comment]
You can make them manually while you're waiting for this https://docs.pact.io/pact_broker/tags#creating-and-using-tags

**Comment by neilcampbell** [comment]
@tawfiknouri You want to be using the `PactBroker` method not `PactUri`. That will give you `enablePending`, `consumerVersionTags`, `providerVersionTags` and `consumerVersionSelectors`.

**Comment by tawfiknouri** [comment]
@neilcampbell 
Yes, Using the `PactBroker ` method is the best way when provider build triggered by the provider team, but for **build triggered by a **contract changed webhook**** i think we have 2 options:

1. Update the `PactBroker `to support single pact url (triggered  by webhook)
2. Add tags support to `PactUri `method

**Comment by bethesque** [comment]
In the underlying CLI Neil, the provider version number, tags, and publish flag are independent of whether the pact was retrieved by URL or from the 'automatically return all the pacts' api.

So you can actually provide:
((One or more Pact URLs, which will be retrieved individually) and/or (Pact Broker base URL and the provider name, and consumer version selectors, which will automatically fetch the relevant pacts for the provider)) optionally and (publish flag true, provider version, provider tags)

Sorry - this not not well documented in the CLI docs, I apologise.

As Tawfik mentioned, being able to publish the verification results with tags and version number for the pact URL is required to be able to implement the recommended 'contract changed' webhook workflow, where the provider just verifies the pact that has changed.

In the meantime Tawfik, if your newly published pact has a feature branch tag on it, you could pass through the tag instead, and run the standard verification task with only that consumer tag. I have recently added the ability to specify the consumer name in the selector, but I don't think that's exposed in the .net impl yet. If your tag is unique amongst the consumers, it should work though. The only drawback with this technique is that the webhook URL contains some metadata that can make downstream webhooks more accurate, but you may not be using any of these features yet (publishing git statuses?)

**Comment by neilcampbell** [comment]
@tawfiknouri sorry I should have ready the original issue in a bit more details :D

@bethesque I do remember you saying that both urls supplied, however I could not think of a common scenario where you'd want to do that for a single verification run. I'm still a little confused about why only `pactVerifier.PactUri` can be used. Is it because the url from the webhook is deep linked to a specific pact version or something like that?

@tawfiknouri Probably the best option at this stage is allow the relevant options to be optionally supplied to the `PactUri` method. Out of `enablePending`, `consumerVersionTags`, `providerVersionTags`, `consumerVersionSelectors`, `includeWipPactsSince`, which make logical sense to make optionally available?

**Comment by tawfiknouri** [comment]
@bethesque the the second way is adding the **commit id** as tag in **consumer pipeline**

Then, when build is triggered by webhook we can use the **PactBroker** method and the **consumerVersionSelectors with ** **commit id** as (provided by webhook)

@neilcampbell for me adding the consumer version to consumerVersionSelectors can resolve this problem.

**Comment by bethesque** [comment]
> Is it because the url from the webhook is deep linked to a specific pact version or something like that?

Yes, exactly. It's so you only verify the single pact that has changed. The URL from the webhook also has some extra metadata in it that allows accurate reporting of consumer and provider shas when you do things like reporting github commit statuses.

You wouldn't generally use both the URL and the 'automatic fetching' at the same time, but when you are using the URL, you need to be able to set the provider version, provider tags, and publish verification results flag.

So the grouping of the options goes:

* webhook scenario: (one or more pact urls) + (publish flag, provider version, provider version tags)

OR

* normal provider build scenario: (pact broker url, provider name, consumer version selectors, pending flag, wipPactsSince) + (publish flag, provider version, provider version tags)

**Comment by bethesque** [comment]
I've updated the usage docs to explain this better:

https://github.com/pact-foundation/pact-provider-verifier#usage

**Comment by neilcampbell** [comment]
@tawfiknouri Did you mean `providerVersionTags` instead of `consumerVersionTags` to `PactUri` as @bethesque mentioned above? Just want to make sure that will solve your issue.

**Comment by tawfiknouri** [comment]
@neilcampbell yes !(sorry for the misunderstanding)
I update my message

**Comment by adamrodger** [comment]
v4.0 provides a much more flexible approach using the new Rust core library and a fluent API
