### ISSUE TITLE
Migrate library to Rust standalone implementation

### ISSUE THREAD

**Issue by alastairs** [pact-foundation/pact-net#254]
The new Rust reference implementation offers a number of benefits over the original Ruby standalone implementation:

 - Foreign Function Interface native library to interop directly, rather than process-wrangling Ruby
 - smaller download (no Ruby runtime, just Pact goodness)
 - the native library for each platform could be bundled in the NuGet package
 - full Pact 3 support (and, going forward, Pact 4)
 - better performance?

I have begun work on this issue, and am tracking the work in my fork [here](https://github.com/alastairs/pact-net/projects/1).

**Comment by adamrodger** [comment]
The `feature/4.0.0` branch is now migrated to the Rust core implementation for a future 4.0.0 release
