### ISSUE TITLE
Changing Upon Receiving description doesnt remove old run from pact file

### ISSUE THREAD

**Issue by Lysandros-SLR** [pact-foundation/pact-net#256]
New to pact testing but I have noticed that if I have a unit test with a description via the UponReceiving call and run it once and then go and change the description and run it again that my pact file now has two entries in it one being with the old description even though there is no test that has that description in my consumer.

Is this expected behavior? How do I prevent this from happening? I've tried deleting the pact file hoping that it would get regenerated correctly but I still end up with 2 entries.

Im using .net core 3.1

Thanks.

**Comment by mefellows** [comment]
This sounds like an issue with the mock server hanging around after your tests.

Are you properly shutting down the service afterwards?

![Screen Shot 2020-08-10 at 11 46 39 am](https://user-images.githubusercontent.com/53900/89746912-920c0b80-daff-11ea-9e32-a2f17ba14094.png)

**Comment by Lysandros-SLR** [comment]
Hi. So I had this part correct but I think it was that my provider unit test wasnt also marked as IDisposable. After adding that I havent seen this be an issue anymore. Its also possible a previous run had caused it to happen. Either way thanks for the help

**Comment by mefellows** [comment]
Great to hear!
