### ISSUE TITLE
PactVerifier doesn't publish verification results to the pact broker 

### ISSUE THREAD

**Issue by billysoomro** [pact-foundation/pact-net#260]
Hi,

My provider tests verify pacts successfully but they don't publish the verification results despite setting the PublishVerificationResults flag to true in the PactVerifierConfig. Here's a full sample of my code:

        [Fact]
        public void RunProviderVerification()
        {
            var config = new PactVerifierConfig
            {
                Outputters = new List<IOutput> { new XUnitOutput(_output) },
                Verbose = true,
                ProviderVersion = "1.0.0",
                PublishVerificationResults = true
            };
            
            var pactUriOptions = new PactUriOptions("someUsername", "somePassword"));

            new PactVerifier(config)
                .ServiceProvider("SomeConsumer", "https://someProviderApi.com")
                .HonoursPactWith("SomeProvider")
                .PactBroker("https://somePactBroker.net/", pactUriOptions)                
                .Verify();
        }

Please advise.

Thanks,
Billy

**Comment by mefellows** [comment]
Can you please share which version of the pact broker you're using and as much debug level logging you can share?

```
            .ServiceProvider("SomeConsumer", "https://someProviderApi.com")
```

Also just checking that that's not real code? If you have indeed put the consumer name in there, I might not expect it to find any pacts to verify.

**Comment by bethesque** [comment]
Can you explain why the consumer and provider names the opposite way to what would be expected? Also, if you are just fetching pacts from a broker, you only need to give the provider name and the broker URL. You should not specify the consumer name.

**Comment by billysoomro** [comment]
Thanks Beth, you're absolutely right. The consumer and the provider names were the wrong way round!

**Comment by billysoomro** [comment]
> Can you please share which version of the pact broker you're using and as much debug level logging you can share?
> 
> ```
>             .ServiceProvider("SomeConsumer", "https://someProviderApi.com")
> ```
> 
> Also just checking that that's not real code? If you have indeed put the consumer name in there, I might not expect it to find any pacts to verify.

All good now,  the consumer and the provider names were the wrong way round as Beth pointed out. The pact broker version is 2.59.2.
