### ISSUE TITLE
2.6.1 version seems to be broken with ruby-standalone 1.88.14

### ISSUE THREAD

**Issue by thomas-girotto** [pact-foundation/pact-net#264]
Hello,

i have the following error with 2.6.1 version when i run my provider tests:

```
pact-win32/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/resolver.rb:328:in `block in verify_gemfile_dependencies_are_found!': You have requested: (Bundler::GemNotFound)
  pact = 1.55.5

The bundle currently has pact locked at 1.51.1.
```

The problem comes since i referenced ruby-standalone 1.88.14 #263 
@bethesque do you think this standalone version has a problem in its dependencies ?

**Comment by bethesque** [comment]
It definitely looks like an issue with the standalone, but I can't reproduce it

![image](https://user-images.githubusercontent.com/446228/95822782-492f3800-0d78-11eb-915c-8bf339ed916a.png)

Are you sure that's the version with the issue? It's the very latest one, which only came out yesterday I think.

**Comment by thomas-girotto** [comment]
OK i cleaned my nuget cache and it's working fine, not sure what happened that lead to this issue though, but it seems that was more something related to my local state... Sorry about this issue.
I'm sure of the version, i needed to get the "PAT" related PR from pact-ruby in my pact-net lib, and i can confirm it's now hidden in the logs :)
Thx

**Comment by bethesque** [comment]
Awesome. Glad it's fixed.
