### ISSUE TITLE
Pact Verification seems to not publish results

### ISSUE THREAD

**Issue by opuech** [pact-foundation/pact-net#265]
From https://dev.azure.com/OlivierPuech/ATQC20-AvoidEnd2End/_git/UnitedColors
when we execute 
  docker build -f Service\Dockerfile . --build-arg BUILD_NUMBER="1.2" --target testrunner -t unitedcolors-testrunner
  docker run --rm unitedcolors-testrunner 
the results should be published. it is not the case :
 ex: http://pact.condensedcow.com/
 [my log tests execution](https://github.com/pact-foundation/pact-net/files/5419767/logs.txt)
Did i miss something ?

)

**Comment by opuech** [comment]
> From https://dev.azure.com/OlivierPuech/ATQC20-AvoidEnd2End/_git/UnitedColors
> when we execute
> docker build -f Service\Dockerfile . --build-arg BUILD_NUMBER="1.2" --target testrunner -t unitedcolors-testrunner
> docker run --rm unitedcolors-testrunner
> the results should be published. it is not the case :
> ex: http://pact.condensedcow.com/matrix/provider/GREEN/consumer/BLUE
> [my log tests execution](https://github.com/pact-foundation/pact-net/files/5419767/logs.txt)
> Did i miss something ?
> 
> )

i solved the issue by replacing this :
.PactBroker(_pactBrokerUrl, enablePending: true, consumerVersionSelectors: new List<VersionTagSelector> { new VersionTagSelector("dev", null, null, false, true) })
by this
.PactBroker(_pactBrokerUrl, enablePending: true, consumerVersionTags: new List<string> { "dev" }, providerVersionTags: new List<string> { "dev" }, consumerVersionSelectors: new List<VersionTagSelector> { new VersionTagSelector("dev", null, null, true) })

**Comment by bethesque** [comment]
Can you include the link to the file that contains your verification configuration? I tried searching in the project, but it says it's still indexing.

**Comment by bethesque** [comment]
Assuming you have `PublishVerificationResults` set to true, as per https://docs.pact.io/implementation_guides/net/readme#publishing-provider-verification-results-to-a-broker ?

**Comment by opuech** [comment]
- the file that contains your verification configuration : https://dev.azure.com/OlivierPuech/ATQC20-AvoidEnd2End/_git/UnitedColors?path=%2FTests%2FTests%2F2Grey%2FFromBlueTests.cs
- yes PublishVerificationResults is set to true, i don't use .PactUri but i used .PactBroker

Thank you

**Comment by bethesque** [comment]
Does your CI actually have a BUILD_NUMBER environment variable? That's just a way to detect whether or not you're running the test on CI. I personally would check if "CI == 'true'" because most CI systems set that.

**Comment by bethesque** [comment]
Btw, it's not meant to publish from your local environment. It's only meant to publish from CI.

**Comment by opuech** [comment]
Hello Beth,

Yes a CI problem... there were a problem on my DockerFile (use of ARG without ENV to load the BUILD_NUMBER variable).

Thank you for your help
