### ISSUE TITLE
Is it possible to send Custom POST request body?

### ISSUE THREAD

**Issue by nithinacv** [pact-foundation/pact-net#279]
I saw this [post](https://github.com/pact-foundation/pact-net/issues/209) about custom request headers using PactVerifierConfig and started wondering if it could be possible to send a request with custom body for any of the endpoints in the pact.

The use case for me is that I am trying to test for this POST endpoint, that takes an ID of something to create a new entry for it. Because it cannot re-use an ID to create this new entry, I am generating it during run-time in my provider tests.

The consumer tests (in .js) that generate the pacts, do so with a body provided using `body:` parameter in the `addInteraction({withRequest: {...` block.

**Comment by mefellows** [comment]
You would usually use provider states so that you could re-use an ID. Can you please elaborate on your use case a little more?

**Comment by nithinacv** [comment]
So, I am trying to write a provide test for a POST endpoint that takes an `id` element in the request body, like this:
```
before(() => provider.setup()
  .then(() => provider.addInteraction({
      state: "an item is created",
      uponReceiving: "create a sale for given item",
      withRequest: {
        method: "POST",
        path: '/api/sale',
        body: {
          "id": "1f2b742e-cc01-43ce-97ef-d18a80745ed6",
          "itemId": "510e3fce-6564-4691-9ca2-2108685aefd3"
        }
      },
      willRespondWith: {
         status: 201,
         body: {
            newSaleId: string('80ed120c-2370-444c-a5a2-fb58d8b4d2ec')
         }
      }
  })
)
```

In my provider test, I am calling some endpoints to create the item whose `itemId' I would like to use in the body of the request that is used to verify POST call from the Pact Contract. 
I am not doing anything in the Provider test yet. I am just creating the item using an API call, and then using Pact Verifier to verify. Like this...

```
[Test]
public void EnsureConsumerAuctionHouseHonoursOrderServiceContract()
{
    _myApiClient.CreateItemForSale();
    _pactVerifier
    .ServiceProvider("sales", _serviceUri)
    .HonoursPactWith("listings")
    .PactUri(_pactDirectory)
     .Verify();
}
```
 
The problem I have here is that the Pact Verifier always uses the body from the pact contract. 
I do not know of a way to override the body for the request with something of my own.
