### ISSUE TITLE
Verification failing to match type on double number

### ISSUE THREAD

**Issue by ngufra** [pact-foundation/pact-net#280]
The service I test returns a long floating point number. The consumer test passes and generate a pact file but when running the provider test, the verification fails. it seems it cannot parse the number into a float and gives it a type NilClass.

My consumer test specifies in the expected body 

```
	jitter = new
	{
		value = Match.Type( 0.6742424242424242 )
	},
```
The pact looks like 
```
"jitter": {
     "value": 0.6742424242424242
 } 
 
 "$.body.aggregations.site.buckets[*].samples.buckets[*].jitter.value": {
        "match": "type"
   }
```
When running provider test, the service returns 
```
"jitter":{"value":0.696969696969697}
```

And the test fails with

```
            {
                 "jitter": {
 -                  "value": Float
 +                  "value": NilClass
            }
* Expected a Float (like 0.6742424242424242) but got nil at $.[...] .jitter.value
```

So it seems when parsing the content, it cannot parse 0.696969696969697 as a number and then fails to verify a match to type Float.

**Comment by bethesque** [comment]
That's very strange. Can you have a go at replicating it using this project please? https://github.com/pact-foundation/pact-ruby-standalone-e2e-example

I've tried to replicate it in a Ruby 2.2 terminal as so:

```
require 'json'
JSON.parse({ foo: 0.6742424242424242}.to_json)
=> {"foo"=>0.6742424242424242}
```

That is not showing any issue. Can you find the pact.log that gets generated during the tests and find the request/response logs for this interaction please.

**Comment by ngufra** [comment]
I did more testing.

I was processing a large set of data and some were null; so NilCalss was correct in those cases.

User error.
Oops.
Thank you.
