### ISSUE TITLE
Looking for a new project co-maintainer

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-net#282]
We are on the lookout for a new .NET framework maintainer to take Pact through to its next phase of the journey.

Pact has experience massive growth over the past ~6 years since this package was created. We now have ~12 languages, global maintainers and a huge community using Pact every day to reduce the pain of integration testing microservices, and distributed systems.

## Roadmap

Whilst there is always a backlog issues and feature requests to work through, the following should give a sense of the impact the next core maintainer can have on the direction of the framework:

* Introducing message support into the framework
* Migrating from the Ruby shared core to Rust
* Review of the API suitability for .NET Core and modern .NET practices
* Implementing the [plugin interface](https://github.com/pact-foundation/pact-specification/issues/83)

If you're interested in taking over or becoming a regular contributor, please join our community workspace at slack.pact.io / https://pact-foundation.slack.com/ and make yourself known to the #pact-net channel and we'll connect you to the maintainer community.

Lastly, I want to thank @neilcampbell for his contributions over the years - in code, in ideas and in person. As rewarding as it is, we know that maintaining and owning an OSS project is like raising a child - it can be tiring at times. You've done the project proud!

**Comment by mefellows** [comment]
@adamrodger do we want to close this or are you open to having another join you?

**Comment by adamrodger** [comment]
Yeah good point
