### ISSUE TITLE
Can I set the http client used by the pact verifier

### ISSUE THREAD

**Issue by chivandikwa** [pact-foundation/pact-net#283]
Can I set the http client used by the pact verifier? It seems as if at some point this was possible by looking at the other readme available in this repo. Is this still possible, this would be quite useful.

**Comment by chivandikwa** [comment]
Thanks for the response. I was already using the WebApplicationFactory for my integration tests and it would have been nice to use the same. I am also having trouble with the implementation shown in the samples. It works for the provider state by gets a 404 for actual calls. But this I guess I will pursue elsewhere.

**Comment by mefellows** [comment]
No worries. I'll close this off then.

If you want to chat about the 404, i'd recommend jumping in to http://slack.pact.io/ and chatting about it in #pact-net channel.

Usually, you can see what's going on by looking at the `pact.log` file (or whatever you've chosen to write the output to), which should tell you the difference between what your code is doing and what's expected.

**Comment by cmdkeen** [comment]
I've found a (messy for now) mechanism of getting this working using WebApplicationFactory and being able to inject state from within the test class - by proxying the requests from the pact verifier. This also has the advantage of not needing to have the provider running separately.

I used the AspCore.Proxy [library](https://github.com/twitchax/AspNetCore.Proxy), though I'm not sure how useful that actually was given the hacking required to pass in the HttpClient I wanted it to use.

      private readonly WebApplicationFactory<Provider.Startup> _factory;
      private readonly HttpClient _client;

      private class FakeClientFactory : IHttpClientFactory
      {
          private readonly HttpClient _client;

          public FakeClientFactory(HttpClient single)
          {
              _client = single;
          }

          public HttpClient CreateClient(string name) => _client;
      }

      public ProviderApiTests(ITestOutputHelper output, WebApplicationFactory<Provider.Startup> factory)
      {
          _outputHelper = output;
          _providerUri = "http://localhost:9002";
          _pactServiceUri = "http://localhost:9002";

          var events = new List<Provider.EventModel> ();
          _factory = factory;
          _client = factory.WithWebHostBuilder(builder =>
          {
              builder.ConfigureTestServices(services =>
              {
                  services.AddSingleton(events);
              });
          })
              .CreateClient();

          _webHost = WebHost.CreateDefaultBuilder()
              .UseUrls(_pactServiceUri)
              .UseStartup<TestStartup>()
              .ConfigureServices(services =>
              {
                  services.AddSingleton(new FakeClientFactory(_client));
                  services.AddSingleton(events);
              })
              .Build();

          _webHost.Start();
      }

I started with the workshop code but it's currently been modified to be employer specific. I'll try and revert back to sample code and share it.
