### ISSUE TITLE
Publishing pact to PactBroker raise NotFound error

### ISSUE THREAD

**Issue by jacekmlynek** [pact-foundation/pact-net#285]
Hi,

I didn't find similar issue, so decide to raise this one.  Happy to close if this duplicate something else.

**The problem:**
When I am trying to publish a new pact with new consumer version using URI with sub domain (e.g. `http://pactbroker.mymachine.office.int.myCompany.com`) pact-net client is unable to add a new consumer pact version. 

Request to PactBroker which looks like this:
`PUT http://pactbroker.mymachine.office.int.myCompany.com/pacticipants/Foo/versions/1.10.0-jml-canIdeploy-487065.1+3a91c3e/tags/features%2Fjml_canIdeploy_487065`

**End with 404 - NotFound.**

Saying that I have checked and url `http://pactbroker.mymachine.office.int.myCompany.com/pacticipants/Foo/versions` **works ok - return all versions.**

From general technical point of view I may understand why PactBroker return 404, since, version: `1.10.0-jml-canIdeploy-487065.1+3a91c3e` is a new version and do not exist in PactBroker, but this is a whole point, isn't it?. Add pact with new customer version. I used to use urls like e.g. **http://myMachineName:9292** double check that  based on the same versions and it is works as usually. Catch traffic:

`PUT http://myMachineName:9292/pacticipants/Foo/versions/1.10.0-jml-canIdeploy-487065.1+3a91c3e/tags/features%2Fjml_canIdeploy_487065`

Returns: 201

In this case I have catch yet another request:

`http://myMachineName:9292/pacts/provider/Bar/consumer/Foo/version/1.10.0-jml-canIdeploy-487065.1+3a91c3e `

which also return 201.

From my point of view I have two different behavior of pact-net and the only difference to me is PactBroker url schema.

Thanks,
Jacek.

**Comment by bethesque** [comment]
Can you do a few experiments for me.

Try setting the environment variable VERBOSE=true and see if you get the HTTP logs printed out when you publish (I'm not sure if you have the version which supports that, so it may not work). 

Try publishing the pacts with the pact-cli. You can use the docker image [here](https://hub.docker.com/r/pactfoundation/pact-cli)  or the pact-ruby-standalone [here](https://github.com/pact-foundation/pact-ruby-standalone/releases) (which is what Pact.NET is using under the hood). You can turn on verbose by setting the `--verbose` option with both of these.

**Comment by jacekmlynek** [comment]
Ok, I think I did what you have asking for, but I am not sure what is comes after my investigation.  I didn't have a chance to look into pact-net code yet, maybe I should do that.

Few details which maybe helpful:

1. I am using pact-net client version 2.4.6
2. PactBroker client version 1.28.3
3. PactBroker version 2.30

>Try setting the environment variable VERBOSE=true and see if you get the HTTP logs printed out when you publish (I'm not sure if you have the version which supports that, so it may not work).

When I am publishing pacts using pact-net I do not see any additional info neither in logs nor in console. Additionally I have checked PactBroker logs, but there is no much there neither:
`D, [2021-04-02T16:07:03.574212 #7868] DEBUG -- : (0.000222s) SELECT NULL
D, [2021-04-02T16:07:03.574471 #7868] DEBUG -- : (0.000184s) BEGIN
D, [2021-04-02T16:07:03.575478 #7868] DEBUG -- : (0.000168s) COMMIT`

When I have tried publish pact using pact-broker client:
`pact-broker publish PATH/bin/.pact/pats/foo-bar.json --verbose --consumer-app-version=1.11.0-jml-canIdeploy-487065.1+4db0f23 --tag="features/jml_canIdeploy_487065" --broker-base-url=http://pactbroker.mymachine.office.int.myCompany.com/`

It works as expected - new pacts are added to PactBroker and the communication is as follows:

1. Request: PUT /pacticipants/foo/versions/1.11.0-jml-canIdeploy-487065.1%2B4db0f23/tags/features%2Fjml_canIdeploy_487065, Response: **404**
2. Request: `GET /pacts/provider/bar/consumer/foo/version/1.11.0-jml-canIdeploy-487065.1%2B4db0f23`, Response: **404**
3. Request: `PUT /pacts/provider/bar/consumer/foo/version/1.11.0-jml-canIdeploy-487065.1%2B4db0f23`, Response: **201**

As I have mention at the beginning I am not entire sure what this is mean. I will try take a look on pact-net client code. Additionally I can update pact-net client, but PactBroker is a bit more complex task in my company (will need like a moth to do that), so I am not entire sure to which version I can update pact-net so it still will be able to collaborate with my PactBroker. Hmm, sounds like case for contract test :). Maybe there is some PactBroker matrix for its clients, since they are not release together?

Please let me know what you think about it and if can do something more, to solve or at least to understand nature of this problem.

**Comment by jacekmlynek** [comment]
Finally I had a chance to take a look on pact-net client and I have found my answers.

**Conclusion**

Root cause was on my side, however pact-net client and ruby cli works in a different wayt. The biggest difference is that pact-net  will fail, when it receives 404 status code for adding tag request. Pact cli on the other hand, handle it gracefully so other requests can be made. Besides that the order and number of operation/request to PactBroker in cli is different. In pact cli we have: `create_consumer_versions && apply_tags && publish_pacts` in pact-net: ` apply_tags && publish_pacts`. I can try to change that if we think that is should works more like a ruby client.

**Root cause**

The only reason why I find true problem is because I have broken our branch name rule and instead of follow git flow convention, in this case `features/some_name` I just create branch with name: `some_name` As a result I was unable to reproduce previous problem. Seeing this I already know that it must have something to do with escaping `/` character and it was. BTW as probably many of you I am using branch name as a tag. I just don't know why it is also related to sub domain based uri (not direct uri). The answers was nginx revers proxy. Proxy when processing the request decode the param and instead of `/tags/features%2Fsome_name` send `/tags/features/some_name` request, which must end up with 404. Changing proxy settings, solved my issue. Shame on my that I didn't catch this earlier. 

I will keep this open for few days. @bethesque please let me know if you think that it would be valuable to adjust pact-net client to work more close to ruby cli I can make PR with needed changes.

**Comment by bethesque** [comment]
I'm about to write a new all-in-one endpoint to publish pacts with that will fix the messy publishing process.

https://github.com/pact-foundation/pact_broker/discussions/413

Can you hang about until I've got it ready and just update the code to use that instead?

**Comment by bethesque** [comment]
Please follow the PR here https://github.com/pact-foundation/pact_broker/pull/420

**Comment by bethesque** [comment]
This endpoint can be used now https://github.com/pact-foundation/pact_broker/blob/master/lib/pact_broker/doc/views/index/publish-contracts.markdown

The issue can be closed.
