### ISSUE TITLE
PactVerifier fails when pact broker username contains at sign

### ISSUE THREAD

**Issue by nadiiaboichuk** [pact-foundation/pact-net#289]
PactVerifier fails with the following error when pact broker username contains at sign:
```
 /.../netcoreapp3.1/pact-linux-x86_64/lib/ruby/lib/ruby/2.2.0/uri/generic.rb:400:in `check_user': bad component(expected userinfo component or user component): *** (URI::InvalidComponentError)
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/ruby/lib/ruby/2.2.0/uri/generic.rb:377:in `check_userinfo'
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/ruby/lib/ruby/2.2.0/uri/generic.rb:443:in `userinfo='
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.55.5/lib/pact/provider/pact_uri.rb:33:in `block in to_s'
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.55.5/lib/pact/provider/pact_uri.rb:33:in `tap'
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.55.5/lib/pact/provider/pact_uri.rb:33:in `to_s'
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.55.5/lib/pact/provider/rspec.rb:26:in `honour_pactfile'
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.55.5/lib/pact/provider/pact_spec_runner.rb:132:in `block in initialize_specs'
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.55.5/lib/pact/provider/pact_spec_runner.rb:126:in `each'
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.55.5/lib/pact/provider/pact_spec_runner.rb:126:in `initialize_specs'
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.55.5/lib/pact/provider/pact_spec_runner.rb:34:in `run'
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.55.5/lib/pact/cli/run_pact_verification.rb:69:in `run_with_pact_uri_object'
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.55.5/lib/pact/cli/run_pact_verification.rb:50:in `run_specs'
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.55.5/lib/pact/cli/run_pact_verification.rb:21:in `call'
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-1.55.5/lib/pact/cli/run_pact_verification.rb:13:in `call'
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.32.1/lib/pact/provider_verifier/app.rb:171:in `verify_pact'
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.32.1/lib/pact/provider_verifier/app.rb:43:in `block in call'
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.32.1/lib/pact/provider_verifier/app.rb:42:in `collect'
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.32.1/lib/pact/provider_verifier/app.rb:42:in `call'
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.32.1/lib/pact/provider_verifier/app.rb:34:in `call'
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.32.1/lib/pact/provider_verifier/cli/verify.rb:47:in `verify'
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.32.1/lib/pact/provider_verifier/cli/custom_thor.rb:17:in `start'
 	from /.../netcoreapp3.1/pact-linux-x86_64/lib/app/pact-provider-verifier.rb:33:in `<main>'
```

PactVerifier usage:
```
private void VerifyContractWithConsumer(string consumerName)
{
    var pactUriOptions = new PactUriOptions(
        Environment.GetEnvironmentVariable("PACT_BROKER_USERNAME"),
        Environment.GetEnvironmentVariable("PACT_BROKER_PASSWORD"));

    var pactBrokerBaseUrl = Environment.GetEnvironmentVariable("PACT_BROKER_BASE_URL");

    IPactVerifier pactVerifier = new PactVerifier(_config);
    pactVerifier
        .ServiceProvider("Weather Forecast API", ProviderUri)
        .HonoursPactWith(consumerName)
        .PactUri(
            $"{pactBrokerBaseUrl}/pacts/provider/Weather%20Forecast%20API/consumer/Weather%20Forecast%20API%20Consumer/latest",
            pactUriOptions)
        .Verify();
}
```
Different pact broker user without at sign works OK.
Any help is highly appreciated. Thanks.

**Comment by mefellows** [comment]
Hmm. Looks like it needs to use the base64 encoded header instead the URL scheme method.

**Comment by greghicks01** [comment]
hi @nadiiaboichuk,

I am looking into this issue. 

Can you show a sample name with a sign, just to be sure I have understood what you mean when you say "with a sign"

I note you're on a Linux distro (I have a mac and windows and can either VM or EC2 Linux instances) which Linux distro did u use?

And I will also look into @mefellows comment to try with the base64 header.

**Comment by nadiiaboichuk** [comment]
Hi @greghicks01,

> When you say at sign, do you mean @?

yes, @ symbol in the username causes this error. Once we remove @ symbol from the username it worked ok, so we are not blocked by this issue.

Regarding Linux distro, here are some details:

![Screenshot 2021-04-29 145518](https://user-images.githubusercontent.com/59834581/116547318-63d39380-a8fb-11eb-812f-d39f924de086.png)

Thank you.

**Comment by greghicks01** [comment]
hi @nadiiaboichuk and @mefellows 

Based on the symptoms, presence of an @ symbol in the username for Basic Auth, I investigated how that is actually built. RFC 2617 describes a plain text URL in basic auth has a few forms, such as
`http://username:password@example.com/`

There is an issue if we have either parameter with @ or : because it breaks the URL when used.

To help me uncover the unit test coverage, VS Community extension **Fine Code Coverage** was used to locate test gaps.
![image](https://user-images.githubusercontent.com/8934535/116689826-e5aae600-a9fb-11eb-8bca-f57992e30a2e.png)
![image](https://user-images.githubusercontent.com/8934535/116691573-518e4e00-a9fe-11eb-922d-7c59669a91f2.png)
![image](https://user-images.githubusercontent.com/8934535/116691653-7682c100-a9fe-11eb-939d-6ddfde1672e9.png)

Examing the codebase called by @nadiiaboichuk we can see some uncovered code, and no range checked for the offending @ symbol.

If we encode the username/password this enables the use of @ and : in the username or password o base64, we negate the range check. Further down we have the conversion to base64 stored in AuthorizationValue.

My conclusion without digging further: 
- we are either not passing AuthorizationValue to ruby or
- ruby is reading the wrong value (sight unseen).

I will need to dig into the Ruby repo for completeness.

Your thoughts matt?

**Comment by bethesque** [comment]
Looks like it's here in the to_s method. It's probably not functional. https://github.com/pact-foundation/pact-ruby/blob/master/lib/pact/provider/pact_uri.rb#L3

**Comment by bethesque** [comment]
There will be a new version of the standalone released by the Rube Goldberg machine. Can someone please update and release.

**Comment by mefellows** [comment]
Thanks Beth.

Does it use the base64 encoded auth under the hood or URI based?

**Comment by greghicks01** [comment]
Hi Everyone

I have added more tests in .NET around the verifier classes, including a username/password with the @.

In the PactVerifierConfig there appears to be a bug in the deprecated CustomHeader (PactVerifierConfig.cs Lines 17-31)

![image](https://user-images.githubusercontent.com/8934535/116800526-4eea4080-ab45-11eb-866d-d0bdba75020e.png)

Line 26 does run, but the original version (above) never removes an updated CustomHeader. resulting in a side effect of the CustomHeaders never removing the old CustomHeader. The test I have written to cover this inspects the CustomHeader Length parameter to have the right length and not contain the old keypair.

I believe we need an integration test for the conditions Beth has above so we can confirm if the hand off to Ruby is working after the fix.

@mefellows happy to take your guidance if this should not be changed

**Comment by greghicks01** [comment]
@neilcampbell @bethesque can i ask for a few minutes of your time to chat about setting up a mock so we confirm the fix in ruby works with the current pact-net? Appreciate your time is valuable.

**Comment by mefellows** [comment]
Let's discuss in the #pact-net-development channel Greg.

**Comment by adamrodger** [comment]
Closed as stale since the release of PactNet 4.x
