### ISSUE TITLE
How to ignore casing

### ISSUE THREAD

**Issue by Blackclaws** [pact-foundation/pact-net#294]
So I've been trying out pact.net and trying to get it to work between two of my services.

However what keeps throwing me off is the fact that the json is compared literally when it doesn't have to be. I'm being quite liberal in my deserialization logic so I don't need to have case sensitive matching. Is there any way to disable this?

To clarify I'm talking about the keys not the contents which I can specify using Matchers as far as I understand it.

**Comment by mefellows** [comment]
I don't believe we can ignore case on the keys themselves, at least, I'm not aware of an option that can do it. I'm not sure I understand the problem here, can the consumer tests not just specify the case sensitive names or am I missing something?

**Comment by Blackclaws** [comment]
The consumer tests do specify the keys they are comfortable with, however since we use case insensitive json deserialization the producer doesn't have to adhere to key casing in order to be compliant with what the consumer expects. 

Hence even if the producer were to change the casing on their keys this would not have any impact whatsoever on the consumer and I'd like for that to be represented in the pact if at all possible.

**Comment by mefellows** [comment]
Thanks, I understand what you're asking.

In my experience, it's the kind of thing that you just don't change very often so I'm not sure outside of theoretical if it's worth building the feature. I'm also not seeing the actual pain point. If the provider changes the serialisation, pact will fail the build so they will just not commit the change.

That being said, the feature may already exist though. 

@bethesque do you know if there is case insensitive key matching mode in the Ruby code?

**Comment by adamrodger** [comment]
At the moment the Ruby core (and also the new Rust core we're migrating to) don't support case-insensitive matching so I'm afraid this isn't possible.

If the Rust core library does start to support it though, we can certainly reopen this issue
