### ISSUE TITLE
Testserver support

### ISSUE THREAD

**Issue by Blackclaws** [pact-foundation/pact-net#295]
So trying this out I've found that Pact.Net starts an additional service for both creation and verification of pacts.

Is there any specific reason other than that it hasn't been done because no one had time that this couldn't be done in memory with TestServer instead? That would completely eliminate the need for any sort of port allocation and the creation of additional actual live servers during the test run.

My best guess is that it simply uses the main pact server/client as the common implementation for all to prevent any need to reimplement the wheel in each language

**Comment by mefellows** [comment]
You're spot on - we use Ruby under the hood (see https://docs.pact.io/wrapper_implementations and https://docs.pact.io/roadmap/feature_support/).

The Ruby process can be quite slow and has a number of other challenges. We are slowly migrating languages to a shared library (written in Rust) which runs a lot faster and solves a lot of these issues.

Aside from the issues alluded to above, is there a particular problem you're experiencing?

**Comment by Blackclaws** [comment]
The problem I was experiencing is that when running multiple Consumer Tests they both interact with the same pact server if the port isn't adjusted for each version. Therefore one test destroyed the pacts generated by the other one and lead to test failures. 

Is there a workaround I should be aware of or just assign a different port for each consumer test?

**Comment by mefellows** [comment]
The current underlying Ruby implementation actually supports this via `merge` write mode. It could be supported by enabling that flag to pass through. See the mock service from https://github.com/pact-foundation/pact-ruby-standalone/releases for more

```
✗ pact-mock-service help service
Usage:
  pact-mock-service service

Options:
      [--consumer=CONSUMER]                                      # Consumer name
      [--provider=PROVIDER]                                      # Provider name
  -p, [--port=PORT]                                              # Port on which to run the service
  -h, [--host=HOST]                                              # Host on which to bind the service
                                                                 # Default: localhost
  -d, [--pact-dir=PACT_DIR]                                      # Directory to which the pacts will be written
  -m, [--pact-file-write-mode=PACT_FILE_WRITE_MODE]              # `overwrite` or `merge`. Use `merge` when running multiple mock service instances in parallel for the same consumer/provider pair. Ensure the pact file is deleted before running tests when using this option so that interactions deleted from the code are not maintained in the file.
                                                                 # Default: overwrite
  -i, [--pact-specification-version=PACT_SPECIFICATION_VERSION]  # The pact specification version to use when writing the pact. Note that only versions 1 and 2 are currently supported.
                                                                 # Default: 2
  -l, [--log=LOG]                                                # File to which to log output
      [--log-level=LOG_LEVEL]                                    # Log level. Options are DEBUG INFO WARN ERROR
                                                                 # Default: DEBUG
  -o, [--cors=CORS]                                              # Support browser security in tests by responding to OPTIONS requests and adding CORS headers to mocked responses
      [--ssl], [--no-ssl]                                        # Use a self-signed SSL cert to run the service over HTTPS
      [--sslcert=SSLCERT]                                        # Specify the path to the SSL cert to use when running the service over HTTPS
      [--sslkey=SSLKEY]                                          # Specify the path to the SSL key to use when running the service over HTTPS

Start a mock service. If the consumer, provider and pact-dir options are provided, the pact will be written automatically on shutdown (INT).
```

The new Rust interface will also support this

**Comment by Blackclaws** [comment]
I'm not talking about merging two files for the same producer, its about two different producers that I am writing consumer tests for. Even though the names of the consumer provider pairs are different they are apparently handled by the same mock-service instance (it appears the first one to bind wins out)

**Comment by mefellows** [comment]
Ah! Right you'll need separate mock servers for each consumer/provider pair (you can reuse but it means you can't then in parallel and you'll need to deal with the lifecycle methods, which I'm not sure are exposed via the .NET lib).

**Comment by adamrodger** [comment]
@Blackclaws Consumer tests for the same consumer/provider pair should never be executing in parallel because they must share the same mock server. The README file shows how to use xUnit test fixture to make sure that consumer tests for the same pair aren't executed in parallel by putting them in the same collection.

You can run multiple mock servers (on different ports) for different consumer/provider pairs though, and then execute those in parallel. That's definitely supported and something I've done before. Define two different xUnit collections and give each collection a unique mock server port.

I'm closing the issue because it's an expected design choice in PactNet with a documented process to follow.
