### ISSUE TITLE
Label of Latest Release Is 3.0.0 - Would Be 2.6.2 More Correct? 

### ISSUE THREAD

**Issue by athurner** [pact-foundation/pact-net#296]
This is a very small issue, but I think the label of the latest release should be 2.6.2 and not 3.0.0 

Thank you for checking

**Comment by mefellows** [comment]
Apologies, bad summary in the release - it should be `3.0.0`. Fixed!

**Comment by adamrodger** [comment]
Once a release is published we can't change its version number according to SemVer I'm afraid. As far as I know it did contain a breaking change (an optional parameter on a public constructor is a breaking change) and therefore bumping the major version was the correct thing to do anyway.
