### ISSUE TITLE
Add 127.0.0.1 as a host option

### ISSUE THREAD

**Issue by Perfspec** [pact-foundation/pact-net#303]
See hardcoded mention of localhost below.
https://github.com/pact-foundation/pact-net/blob/c2b8dfeeeebf2312bb37d7c54137802b117720bc/PactNet/Mocks/MockHttpService/MockProviderService.cs#L33

When running this server in a docker container, localhost is not easily available, whereas 127.0.0.1 is available as the loopback address.

Could the ability to choose 127.0.0.1 be added?

**Comment by garden-party-slug** [comment]
see this pull request for ideas: https://github.com/pact-foundation/pact-net/pull/304
