### ISSUE TITLE
Support Verifier Output in Provider Test Output

### ISSUE THREAD

**Issue by adamrodger** [pact-foundation/pact-net#314]
Currently provider tests can tell you when they fail, but they give you no output from the verifier and so you are unable to determine what the actual errors are.

Adding this support requires additional work in the Rust core library, see: https://github.com/pact-foundation/pact-reference/issues/132

**Comment by adamrodger** [comment]
Closed in favour of #343

**Comment by mefellows** [comment]
Oh, goodness. I somehow missed this yesterday @adamrodger. It's even on the project board! I'm happy for you to kill the other issue and use this one.

See this Slack thread that prompted my to raise the issue: https://pact-foundation.slack.com/archives/C9UTHV2AD/p1638530656072500

**Comment by adamrodger** [comment]
Ha, nah we'll use the other one, then it's at the top
