### ISSUE TITLE
Add support for publishing verification results with a branch using the pact-ruby-standalone

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-net#327]
The Pact Broker now supports branches as first class entities. You can read more about this here: https://github.com/pact-foundation/docs.pact.io/blob/feat/deployments-and-releases/website/blog/2021-07-04-why-we-are-getting-rid-of-tags.md

To allow users to use this feature:

* Upgrade the pact-ruby-standalone to at least version `1.88.70`
* Add an appropriately prefixed "branch" property to the user facing interface (make it match the existing provider name, tag, and version properties)
* Pass the branch through to the pact provider verifier CLI using the parameter `--provider-version-branch`

**Comment by adamrodger** [comment]
I'm not sure we're planning on doing any more Ruby-based releases (3.x and below) in favour of Rust-based releases )4.x and above) so not sure if this will get done.

**Comment by adamrodger** [comment]
Yeah I'd close it. I doubt it's gonna get done

**Comment by mefellows** [comment]
This seems like a fairly trivial change for a useful feature and is key to removing the dependency on tags, in favour of branches/environments/deployments. Given that most Pact .NET users would not be on the new beta, and changing to the 4.x.x line is non-trivial on behalf of the user, why would we not do this?

**Comment by bethesque** [comment]
It should be a very small change and it would be great for the languages to have feature parity for the branches/envs.

**Comment by YOU54F** [comment]
There was a PR done for the change in v3

https://github.com/pact-foundation/pact-net/pull/345 by @mchwalek (thank you!)

however based on this comment https://github.com/pact-foundation/pact-net/pull/345#issuecomment-1011406171 

it stalled, and was closed/continued on the v4 branch

**Comment by mefellows** [comment]
> The existing API is inflexible so I can't see a good way of doing it in a non-breaking way.

Mmm quite a conundrum. A major release of the ruby based package would overlap with the new 4.x.x and cause even more confusion.

Although it's ugly, is a setter method on `PactBrokerConfig` an option e.g. `SetProviderBranch`?

The alternative is that nobody gets the feature.

**Comment by adamrodger** [comment]
I'm not planning on doing any more 3.x feature releases and instead focussing on 4.x and above, so this issue can now be closed.
