### ISSUE TITLE
Add support for publishing pacts with a branch

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-net#328]
### Feature description

Support publishing pacts with branches and a build_url.

### Use case

See https://github.com/pact-foundation/docs.pact.io/blob/feat/deployments-and-releases/website/blog/2021-07-04-why-we-are-getting-rid-of-tags.md

### Details

* To the user facing Pact API, add:
  * String `branch`
  * String `buildUrl`
* Pass the new properties through to the pact-ruby-standalone publish command as:
  * `branch` as the `--branch` property
  * `buildUrl` as`--build-url`

**Comment by adamrodger** [comment]
Fixed in #353 and #356
