### ISSUE TITLE
Allow 'publish verification results' API be extendable without requiring a breaking change 

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-net#340]
The current publish verification results API works like this:

`.PublishResults(version, "prod", "staging")`

There is already an issue raised to support publishing verification results with a [branch](https://github.com/pact-foundation/pact-net/issues/328), and there will be new issues to support the `commit` and `buildUrl` properties in the future (and we can't rule out that there may be more things, like the commit author, that we add in the future.)

We don't want each addition to the publication properties to require a breaking change to the user facing API each time.

**Comment by adamrodger** [comment]
Worth noting that I've mostly done this locally at the moment but not
pushed it up for review yet (I think?)

**Comment by bethesque** [comment]
Some extra context - the entire "pacts for verification" configuration is going to be supported on the broker side soon, so the user will only need to supply the broker URL and the name of the provider. The selectors and all the other config settings will be configured server side. See https://github.com/pact-foundation/pact_broker/discussions/479

**Comment by adamrodger** [comment]
Pretty sure this is done since #353
