### ISSUE TITLE
[v4.x.x] verifier test output is not visible to clients

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-net#343]
In the 4.x.x branch of this project it is not possible to get any logging out of the verifier. The consumer side has had features added so that you can redirect logging to an in-memory sink and then retrieve the logs afterwards for inclusion in test output, but the verifier still logs directly to stdout as if it was invoked via a CLI.

There is a [feature request](https://github.com/pact-foundation/pact-reference/issues/132) to extend the consumer logging support into the provider tests so that the verifier output (with mismatches etc) can also be included in test output.

This is currently a blocker for the new pact-net v4.0.0 release using the Rust core library instead of the Ruby integration.

This issue tracks the upstream work, and any subsequent work required to extract the log output and make it visible to framework users.

**Comment by mefellows** [comment]
@adamrodger I wasn't aware/paying attention, but looks like the FFI interface now has a similar handle-based API for the verifier (see https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_ffi/src/verifier/mod.rs#L91). 

@uglyog tells me this should circumvent the problems you're having with logging, but also is obviously nicer than the existing one, which is essentially wrapping a CLI.

**Comment by adamrodger** [comment]
Sweet. I saw that on the branch a while ago but it wasn't in a release yet.
We should definitely move to that asap.

I should get some time next week to do that.

**Comment by adamrodger** [comment]
Fixed in #356
