### ISSUE TITLE
[PactNet 4.0.0-beta.1] PublishResults options raising an exception

### ISSUE THREAD

**Issue by sl-tawfiknouri** [pact-foundation/pact-net#371]
A very basic example like this throws an exception with when publishing results
```
    [Fact]
    public void VerifyLatestPacts()
    {
        string version = Environment.GetEnvironmentVariable("VERSION");
        string branch = Environment.GetEnvironmentVariable("BRANCH");
        string buildUri = Environment.GetEnvironmentVariable("BUILD_URL");

        var config = new PactVerifierConfig
        {
            LogLevel = PactLogLevel.Information,
            Outputters = new List<IOutput>
            {
                new XUnitOutput(this.output)
            }
        };

        IPactVerifier verifier = new PactVerifier(config);

        verifier.ServiceProvider("My Provider", this.fixture.ServerUri)
                .WithPactBrokerSource(new Uri("https://broker.example.org"), options =>
                {
                    options.ConsumerVersionSelectors(new ConsumerVersionSelector { MainBranch = true, Latest = true })
                           .PublishResults(version, results =>
                           {
                               results.ProviderBranch(branch)
                                      .BuildUri(new Uri(buildUri));
                           });
                })
                .WithProviderStateUrl(new Uri(this.fixture.ServerUri, "/provider-states"))
                .Verify();
    }
}
```

Error

```
  Failed API.Tests.ProductApiContractVerificationTests.EnsureProductApiHonorsPactWithOrderServiceConsumer [118 ms]
  Error Message:
   System.ArgumentNullException : Value cannot be null. (Parameter 'source')
  Stack Trace:
     at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at PactNet.Verifier.InteropVerifierProvider.SetPublishOptions(String providerVersion, Uri buildUrl, ICollection`1 providerTags, String providerBranch)
   at PactNet.Verifier.PactBrokerPublishOptions.Apply()
   at PactNet.Verifier.PactBrokerOptions.PublishResults(String providerVersion, Action`1 configure)
   at API.Tests.ProductApiContractVerificationTests.<EnsureProductApiHonorsPactWithOrderServiceConsumer>b__1_0(IPactBrokerOptions options) in C:\pact-workshop\pact_ffi-product-provider\tests\ProductApiContractVerificationTests.cs:line 70
   at PactNet.Verifier.PactVerifierProvider.WithPactBrokerSource(Uri brokerBaseUri, Action`1 configure)
   at API.Tests.ProductApiContractVerificationTests.EnsureProductApiHonorsPactWithOrderServiceConsumer() in C:\pact-workshop\pact_ffi-product-provider\tests\ProductApiContractVerificationTests.cs:line 67

Test Run Failed.
```
adding the `.ProviderTags("stage"); ` option seems mandatory

**Comment by adamrodger** [comment]
Ah, that's gonna be missing an Array.Empty when something is calling into the interop code.

We definitely need better coverage using a real pact broker in integration tests. One thing that makes that a bit tricky is that different broker versions support different options, and it's not really clear what the support policy of the broker is.

**Comment by mefellows** [comment]
The Pact broker has been backwards API compatible since version 1.x.x. The main trick is that features are always behind a HAL relation, so clients should check that a HAL relation exists before using a new feature. The Rust and Ruby cores do check for these relations, and should present an error if a feature is being used that isn't supported via the broker.

We also recently did some support/maintenance documentation for Pactflow, we can add this to the OSS docs to make that clearer also.

**Comment by bethesque** [comment]
Publishing a verification result never requires a tag. It's recommended, but should not be mandatory. That error is not coming from the Pact Broker.

**Comment by bethesque** [comment]
Also, the clients should not be enforcing anything except the most basic and unchanging validation rules, as they may change over time. They should make the call and ensure that any error from the broker is returned and shown clearly to the user.

**Comment by adamrodger** [comment]
> Publishing a verification result never requires a tag. It's recommended, but should not be mandatory. That error is not coming from the Pact Broker.

Ah yeah sorry, should've made that clear - it's _definitely_ a PactNet issue (and an easy one to fix).

I more meant the awkwardness with the broker is when integration testing - like do you only ever test the latest broker version? Any older broker versions? How do you stand up the broker (does GitHub Actions do the equivalent of `services` like GitLab CI does?)? That sort of thing. There's definitely no problems with the pact broker though :)

**Comment by adamrodger** [comment]
The issue closes automatically when I mention it in a commit message

**Comment by mylesjj** [comment]
How are you setting Environment.GetEnvironmentVariable("BRANCH")?

**Comment by bethesque** [comment]
> The issue closes automatically when I mention it in a commit message

This is so annoying! I wish they'd only close it when the commit was tagged in a release.
