### ISSUE TITLE
Allow Pact Verifier with Pact Broker Source to publish results without BuildUri

### ISSUE THREAD

**Issue by aucubin** [pact-foundation/pact-net#376]
Hi. I am currently migrating a codebase to PactNet v4 Beta versions and would like to publish the Verification results to a pact broker without using the BuildUrl (from PactBrokerPublishOptions).

A basic pactVerifier builder basically looks like this:
```
pactVerifier
  .ServiceProvider("provider", "http://localhost:9000")
  .WithPactBrokerSource(new Uri("http://localhost:10000"), options =>
  {
  options
    .ConsumerTags("master")
    .PublishResults("1.0.0.0", results =>
    {
      results
      .ProviderTags(new string[] {"master"});
    });
  })
  .WithProviderStateUrl(new Uri(_fixture.EndpointUrl, SharedConstants.ProviderStateRoute))
  .Verify();
```
This pactVerifier fails with a NullReferenceException:
```
     System.NullReferenceException : Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
     bei PactNet.Verifier.InteropVerifierProvider.SetPublishOptions(String providerVersion, Uri buildUrl, ICollection`1
   providerTags, String providerBranch)
     bei PactNet.Verifier.PactBrokerPublishOptions.Apply()
     bei PactNet.Verifier.PactBrokerOptions.PublishResults(String providerVersion, Action`1 configure)
```

But it seems like that the pact-ffi function that is used to set these publication options supports not supplying a build url (see https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_ffi/src/verifier/mod.rs#L267) and it is only not allowed by the PactNet Library.

It would be great if that behaviour could be supported by PactNet.

**Comment by adamrodger** [comment]
Ah, yeah that'll be something internally to the builder. It probably does a `buildUri.AbsoluteUri` but `buildUri` is null

**Comment by adamrodger** [comment]
Yep, it's that. Simple one line fix here:

https://github.com/pact-foundation/pact-net/blob/master/src/PactNet/Verifier/InteropVerifierProvider.cs#L108

**Comment by adamrodger** [comment]
Fixed in https://github.com/pact-foundation/pact-net/commit/ed160012ab05cb8434c21fceb97e2700d7e96135
