### ISSUE TITLE
How to pass auth token when using uri source?

### ISSUE THREAD

**Issue by mchwalek** [pact-foundation/pact-net#378]
Hi, I'd like to implement the flow where verification is triggered via webhook. One can configure various options (ncluding authorization token) for WithPactBrokerSource, however for WithUriSource there's no such possibility. How can I pass auth token when using uri source?

**Comment by YOU54F** [comment]
Hi @mchwalek 

Looks like this is a missing feature, see TODO in the code

https://github.com/pact-foundation/pact-net/blob/da591c5f72c35b625535861e9d4e6c18ec52df0a/src/PactNet/Verifier/PactVerifierProvider.cs#L66

This is the `WithPactBrokerSource ` method, you can see it takes a param called `configure` which would contain the options.

https://github.com/pact-foundation/pact-net/blob/da591c5f72c35b625535861e9d4e6c18ec52df0a/src/PactNet/Verifier/PactVerifierProvider.cs#L84

Would happily accept a pull request if you have the time!

**Comment by adamrodger** [comment]
OP is talking about the URI source, not the broker. The broker source
already supports auth tokens but the URI source doesn't.

I'd have to check the FFI to see whether it's supported, but I assume it
is. If so, it would need an overload on the URI source which takes a
configuration builder, similar to the broker source.

**Comment by YOU54F** [comment]
Thanks for the additional context @adamrodger.

Just checking the pact ffi's docs which leads me to 

https://docs.rs/pact_ffi/latest/pact_ffi/verifier/fn.pactffi_verifier_url_source.html

note this is latest, I've not checked what version we are using in pact-net.
