### ISSUE TITLE
Injecting provider states - Example available?

### ISSUE THREAD

**Issue by tl-madhulika-mitra** [pact-foundation/pact-net#389]
Hi,

Just like we have provider states being able to inject values in JVM [here](https://github.com/pact-foundation/pact-jvm/tree/master/consumer#having-values-injected-from-provider-state-callbacks) . Do we have similar support available in Dotnet? I was checking [feature support](https://docs.pact.io/roadmap/feature_support) and it looks like its not yet there, but confirming.

**Comment by adamrodger** [comment]
This isn't currently supported, no.
