### ISSUE TITLE
Pact Net 4.0.0-beta.3 publish is not succeeding - Throwing 403

### ISSUE THREAD

**Issue by tl-madhulika-mitra** [pact-foundation/pact-net#390]
Kindly note I tried the below cases with to publish to broker. 

var pactServiceUri = new Uri(_environment.PactServiceUri, UriKind.Absolute);

I am just using my broker uri as my build uri at this time.

Case 1:
   .PublishResults("0.0.1", results =>
                    {
                        results.ProviderBranch("pact-test")
                            .BuildUri(pactServiceUri);
                    })

Result:
System.NullReferenceException
Object reference not set to an instance of an object.
   at PactNet.Verifier.InteropVerifierProvider.SetPublishOptions(String providerVersion, Uri buildUrl, ICollection`1 providerTags, String providerBranch)
   at PactNet.Verifier.PactBrokerPublishOptions.Apply()
   at PactNet.Verifier.PactBrokerOptions.PublishResults(String providerVersion, Action`1 configure)

Case 2:
.PublishResults("0.0.1", results =>
                    {
                        results.ProviderBranch("pact-test")
                            .BuildUri(pactServiceUri)
                            .ProviderTags("first-test");;
                    })

[ERROR][pact_verifier::pact_broker] Failed to push branch pact-test for provider version 0.0.1
[ERROR][pact_verifier] Publishing of verification results failed with an error: Error with the content of a HAL resource - Request to pact broker URL '<<broker-uri>>/pacticipants/<<providerName>>/branches/pact-test/versions/0.0.1' failed - HTTP status client error (403 Forbidden) for url 
Setup:
<PackageReference Include="PactNet" Version="4.0.0-beta.3" />
<PackageReference Include="PactNet.Abstractions" Version="4.0.0-beta.3" />
<PackageReference Include="PactNet.OSX" Version="3.0.2" />

**Comment by mefellows** [comment]
A `403` means you haven't supplied the correct set of credentials. It's possible you are using read-only credentials (so pacts can be fetched for verification but you can't push results) or don't have permissions to do so.

This is not an error in Pact .NET, but likely the user associated with the credentials does not have the correct permissions. See https://docs.pactflow.io/docs/permissions/ for more on this.
