### ISSUE TITLE
Examples from Samples directory do not work out of the box

### ISSUE THREAD

**Issue by MaciejReszotnik** [pact-foundation/pact-net#399]
When trying to run Sample project "Messaging" and "Readme" I encountered an issue. I ran those on Windows 10.

After running 'dotnet restore' command on 'consumer' and 'consumer.tests' projects when I try to run the tests - be it with 'dotnet test' or via runner in Visual Studio I get the following error:

`C:\Program Files\dotnet\sdk\6.0.300\Microsoft.Common.CurrentVersion.targets(5097,5): error MSB3030: Could not copy the
file "C:\pact3\pact-net\build\windows\x86_64\pact_ffi.dll" because it was not found. [C:\pact3\pact-net\src\PactNet\Pac
tNet.csproj]`

Obviously, if you follow the 'C:\pact3\pact-net\build\windows\x86_64\pact_ffi.dll' path the files is indeed not there - there is no windows folder.

I tried 'dotnet build' again Consumer.tests project - same issue.

One other thing I noticed while inspecting Nuget packages in Visual Studio is that I can see that PactNet is not listed as installed.

Installing official stable version PactNet 3.0.2 and PactNetWindows does not fix the problem. How to solve this?

**Comment by MaciejReszotnik** [comment]
To answer my own question. It seems to me the creator assumed it was abvious to add pact_ffi.dll from external source and then attempt to run the project. This makes sense for PactNet itself, to avoid version management hassle and decouple it from external project. 

However, I think most people are used to the fact that - at least for sample projects - all required files are downloaded once you restore it or run things like package managers.

For these examples a simple quick fix is to substitute Project Reference to non-existing project with PackageReference 

For example for Messaging project one has to make following changes in Consumer.Tests.csproj:

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="5.10.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.10.0" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    **<PackageReference Include="PactNet" Version="4.0.0-beta.5" />**
  </ItemGroup>
  <ItemGroup>
    ****
    <ProjectReference Include="..\Consumer\Consumer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>
</Project>
`

Similar change must be made in Provider.Tests.csproj file:
`<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="5.10.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.10.0" />
    <PackageReference Include="Moq" Version="4.16.1" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="3.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    **<PackageReference Include="PactNet" Version="4.0.0-beta.5" />**
  </ItemGroup>

  <ItemGroup>
    ****
    <ProjectReference Include="..\Provider\Provider.csproj" />
  </ItemGroup>

</Project>
`
I suggest that either a detailed explanation was created how to set up those sample test projects to be able to run them - perhaps in a README file. Alternatively the package references could be added as shown in code excerpt above.

**Comment by adamrodger** [comment]
You have to run the script from the build folder which gets the correct FFI libraries for you, like the CI does.

It has to be done this way because different branches could be using different versions, and I don't want to check in hundreds of MBs of FFI binaries.
