### ISSUE TITLE
Question: How to use Match.Regex on auto generated guid response

### ISSUE THREAD

**Issue by iduras3** [pact-foundation/pact-net#400]
I want to test a post request, where the response is a random generated guid. I tried the following code, but when i use the pact-provider-verifier it checks for the exact guid and throws an error. Can somebody help me.

```
var response = new Guid("cf8f39b4-65bb-451b-964e-50f3e658ddd3");

_pact.UponReceiving("create")
    .WithRequest(HttpMethod.Post, path: BaseUrlPath)
    .WithJsonBody(request)
    .WillRespond()
    .WithStatus(HttpStatusCode.Created)
    .WithHeader("Content-Type", "application/json; charset=utf-8")
    .WithJsonBody(Match.Regex(response.ToString(), ".*")); // used .* to check for all inputs for testing

await _pact.VerifyAsync(async ctx =>
{
  _httpClient.BaseAddress = ctx.MockServerUri;
  var result = await _client.Create(request);

  result.Should().Be(response);
});
```

**Comment by mefellows** [comment]
Can you please share the logs of the verification that is failing? I'd also like to know the pact specification version that is being generated.

It's possible you're generating a v3 spec in .NET but using the Ruby verifier which only supports V2 pacts. See https://docs.pact.io/implementation_guides/cli#provider-verifier for the list of CLI tools, including the latest verifier.

**Comment by iduras3** [comment]
I use the v3 spec in .NET and installed the tools with brew

Here are the logs:
Verifying a pact between service1 and service2
  Create a name
    with POST /api/v1/name
      returns a response which
[32m        has status code 201[0m
[31m        has a matching body (FAILED - 1)[0m
        includes headers
[32m          "Content-Type" which equals "application/json; charset=utf-8"[0m

Failures:

  1) Verifying a pact between service1  and service2 Create a name with POST /api/v1/name returns a response which has a matching body
     [31mFailure/Error: expect(response_body).to match_term expected_response_body, diff_options, example[0m
     [31m[0m
     [31m  Actual: [37m08571132-1a8a-488b-b5de-c0501fe61963[0m[0m
     [31m[0m
     [31m  [0mDiff[0m
     [31m  [0m--------------------------------------[0m
     [31m  [0mKey: [31m-[0m[31m is expected [0m
     [31m  [0m[0m[32m     +[0m[32m is actual [0m
     [31m  [0m[0mMatching keys and values are not shown[0m
     [31m  [0m[0m
     [31m  [0m[0m[31m-cf8f39b4-65bb-451b-964e-50f3e658ddd3[0m
     [31m  [0m[0m[32m+08571132-1a8a-488b-b5de-c0501fe61963[0m
     [31m  [0m[0m[0m
     [31m  [0m[0m
     [31m  [0mDescription of differences[0m
     [31m  [0m--------------------------------------[0m
     [31m  [0m* Expected "cf8f39b4-65bb-451b-964e-50f3e658ddd3" but got "08571132-1a8a-488b-b5de-c0501fe61963" at $[0m

[31m1 interaction, 1 failure[0m

Failed interactions:

[31m* Create a name (to re-run just this interaction, set environment variable PACT_BROKER_INTERACTION_ID="9383a3fda6663e622a4419f51feb56e795082948")[0m

**Comment by mefellows** [comment]
Hi @iduras3. I'd expect to see a warning in those logs ignoring the unsupported matchers. I'm fairly confident that's the issue, however.

Could you please try with the rust based verifier linked above?

**Comment by iduras3** [comment]
The rust based verifier is working
