### ISSUE TITLE
Error while creating a V3 pact with PactNet latest NuGet package 4.1.0

### ISSUE THREAD

**Issue by GaneshMoodys** [pact-foundation/pact-net#413]
I have just upgraded my PactNet NuGet to latest 4.1.0 and the below line of code is giving error
![image](https://user-images.githubusercontent.com/95041721/179562522-d40efd99-e3c5-4ac6-b87c-dcd567617d2d.png)
How do I create Pact object in 4.1.0 of PactNet

**Comment by xeroeugene** [comment]
You are missing a reference to PactNet.Abstractions 4.1.0
![image](https://user-images.githubusercontent.com/59182981/179731962-73b8824c-2d2b-4e97-9f75-f99f898479ec.png)

**Comment by adamrodger** [comment]
@GaneshMoodys  did this fix your issue? I think on new-style SDK projects the `PactNet.Abstractions` dependency will be installed transitively when you install `PactNet`, but on older style SDK projects you'll need to reference it directly.

**Comment by GaneshMoodys** [comment]
hi @adamrodger yes it was fixed when I referenced PactNet.Abstractions explicitly.

thank you
