### ISSUE TITLE
Why is teardown flag not supported for WithProviderStateUrl?

### ISSUE THREAD

**Issue by sprengo** [pact-foundation/pact-net#421]
Why not just add the teardown flag to `WithProviderStateUrl` method of the `IPactVerifierSource` interface and pass it to the `SetProviderState` of the `IVerifierProvider` in the corresponding implementation?

**Comment by adamrodger** [comment]
Added in https://github.com/pact-foundation/pact-net/commit/c2ec3cc4b1a4f65b99aaaa7625af49bf6fbc4700
