### ISSUE TITLE
Add support for AMD64

### ISSUE THREAD

**Issue by danoleary** [pact-foundation/pact-net#423]
My company cannot use pact at present as the tests fail with the following exception during CI:

`System.DllNotFoundException : Unable to load shared library 'pact_ffi' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libpact_ffi: cannot open shared object file: No such file or directory`

We use the official .net SDK 6.0 docker image on the linux/amd64 platform.

Are there any plans to support this platform in the near future? If not, we'd like to fork the repository and add support for linux/amd64. Is there any advice on how to go about that?

**Comment by lehmamic** [comment]
I also would appreciate that. There is a workaround for that:
1. Download the lib here [https://github.com/pact-foundation/pact-reference/releases/download/libpact_ffi-v0.3.14/libpact_ffi-osx-aarch64-apple-darwin.dylib.gz](https://github.com/pact-foundation/pact-reference/releases/download/libpact_ffi-v0.3.14/libpact_ffi-osx-aarch64-apple-darwin.dylib.gz)
2. Copy it to `/user/local/lib` and rename it to `libpact_ffi.dylib`
3. Try to run the tests, maybe you need to approve it in the security center

The native lib must match with the nuget package version.

**Comment by adamrodger** [comment]
I'm unsure whether you're asking for AMD64 or ARM64 support?

AMD64 is already supported and ARM64 is covered by #365 

Compatibility is defined in the README, including the in-progress nature of ARM64 support on OSX, so I'll close this issue for now. Info here:

https://github.com/pact-foundation/pact-net#compatibility
