### ISSUE TITLE
Unable to load DLL 'pact_ffi' if the test project reference another project with PlatformTarget x86

### ISSUE THREAD

**Issue by lucapiccinelli** [pact-foundation/pact-net#425]
Hello, in PactNet 4.3.0 I faced the error `Unable to load DLL 'pact_ffi'` when my test project references another project with PlatformTarget x86.

If no x86 Project is referenced everything is ok.

Entire Exception is

```
System.DllNotFoundException
Unable to load DLL 'pact_ffi' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at PactNet.Interop.NativeInterop.LogToBuffer(LevelFilter levelFilter)
   at PactNet.PactExtensions.InitialiseLogging(PactLogLevel level)
   at PactNet.PactExtensions.WithHttpInteractions(IPactV3 pact, Nullable`1 port, IPAddress host)
   at Consolex86.Test.PactTest..ctor() in D:\workspace\github\pacterror\Consolex86.Test\PactTest.cs:line 16
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
```

I have reproduced and isolated the error here https://github.com/lucapiccinelli/pacterror .
 - **Commit 1**: green test... **no** x86 project referenced
 - **Commit 2**: red test... consolex86 project referenced  

see here https://github.com/lucapiccinelli/pacterror/commits/main

**Comment by adamrodger** [comment]
A process can only run as either x86 or x64. If you reference an x86 project then your process will run as x86 and try to load x86 assemblies, which PactNet doesn't support.

When you remove the reference to the x86 project, your process will run as x64 and thus be able to run PactNet. This is expected behaviour.

**Comment by lucapiccinelli** [comment]
Ok thank you for your kind answer. Just to be sure that I understood It correctly, this means that PactNet doesn't support testing projects compiled with platform target x86?

**Comment by adamrodger** [comment]
Correct - see here for compatibility:
https://github.com/pact-foundation/pact-net#compatibility
