### ISSUE TITLE
Can't build after cloning the repo in Visual Studio: pact_ffi.dll not found

### ISSUE THREAD

**Issue by vcalatayud** [pact-foundation/pact-net#431]
Hi! this is what happened to me and what I did. Just wanted to let it writen in case it could be useful :)

Steps to reproduce:

1. Clone the repo on a Windows system
2. Open the solution in Visual Studio
3. Build

It says that the pact_ffi.dll is not found.

Workaround: 
1. Go to the build folder
2. Run the .sh file to download the native dlls
3. Now you can build

**Comment by adamrodger** [comment]
That's correct, which is what the CI does also.

We don't want to check the FFI libraries in because they're very large, so instead they're restored locally.
