### ISSUE TITLE
Build Breaks when using pactnet packages with a space in the home path

### ISSUE THREAD

**Issue by ronjonesjr** [pact-foundation/pact-net#436]
PactNet.Linux.x64.targets includes the following lines:

<Target Name="FixFilePermissions" BeforeTargets="BeforeBuild" Condition="'$(OS)' != 'Windows_NT'">
    
    <Exec Command="chmod u+x $(MSBuildThisFileDirectory)../tools/pact-linux-x86_64/bin/pact-mock-service" />
    <Exec Command="chmod u+x $(MSBuildThisFileDirectory)../tools/pact-linux-x86_64/bin/pact-provider-verifier" />
    <Exec Command="chmod u+x $(MSBuildThisFileDirectory)../tools/pact-linux-x86_64/lib/ruby/bin/ruby" />
    <Exec Command="chmod u+x $(MSBuildThisFileDirectory)../tools/pact-linux-x86_64/lib/ruby/bin/ruby_environment" />
    <Exec Command="chmod u+x $(MSBuildThisFileDirectory)../tools/pact-linux-x86_64/lib/ruby/bin.real/ruby" />
  </Target>

When MSBuildThisFileDirectory points to a directory with spaces in it, these lines fail.

For example, move your home directory on macOS to a volume with a space in the name (e.g. "Archive Disk").  Then the path to your nuget packages has a space 
/Volumes/Archive Disk/username/.nuget/packages/pactnet.linux.x64/3.0.2/build/PactNet.Linux.x64.targets"

and your build output will show the error...

chmod: /Volumes/Archive: No such file or directory
  chmod: Disk/username/.nuget/packages/pactnet.linux.x64/3.0.2/build/../tools/pact-linux-x86_64/bin/pact-mock-service: No such file or directory

**Comment by adamrodger** [comment]
v3.0.2 is no longer receiving fixes. Please upgrade to PactNet v4.x, which has the added advantage of not needing OS-specific packages installed.

**Comment by ronjonesjr** [comment]
Thanks.
