### ISSUE TITLE
Receiving verification mismatch while trying customised Content-type with Pact-net.

### ISSUE THREAD

**Issue by nikhil4892** [pact-foundation/pact-net#438]
I am trying to perform customer test using Pact net and we are using "application/com.ab.c.orderbook+json" as "Content-Type". But I am getting verification mismatch. The content type I am defining the arrangement is taking only "application/json" and the contract is getting mismatched from the content type "application/com.ab.c.orderbook+json" set while mocking the api. Can't we pass customised content-type in Pact-net? Please suggest how to solve this issue!

**Comment by mefellows** [comment]
I think you're running into https://github.com/pact-foundation/pact-reference/pull/235, which should be solved in the latest version of the core library. 

The latest version of this package has incorporated that (https://github.com/pact-foundation/pact-net/pull/437) so the next release should address this issue.

**Comment by catdolls** [comment]
Hi, I also face the same issue when using PACTNET library version 4.3.0. I used **.WithJsonBody(object body, string contentType)** method and customize the content type to **application/vnd.api+json**. When I run pact verify, I always get the mismatch error message and reponse return **application/json**. @mefellows Could you please help suggest when the fixed will release for PACTNET library or is there any other ways to create mock with customize content type **application/vnd.api+json** by PACT?

**Comment by adamrodger** [comment]
I tried an FFI upgrade recently and had to abandon it due to issues with some changes in it. I'll try again when I've got time now that the FFI issue I reported has been resolved.

**Comment by adamrodger** [comment]
@nikhil4892 please could you re-test on v4.4.0?

**Comment by catdolls** [comment]
@adamrodger Thank you very much for help updating. I upgraded to new version and it works fine.

**Comment by adamrodger** [comment]
Brilliant, glad to hear it 👍
