### ISSUE TITLE
System.BadImageFormatException when using PactNet with an x86 assembly

### ISSUE THREAD

**Issue by marlonjimenezGL** [pact-foundation/pact-net#448]
Hello, we have several .NET Framework projects where we want to use PactNet, but unfortunately they are configured with Platform target: x86 and we can not change that. My question: Is there a way to avoid this System.BadImageFormatException? We have tried many workarounds to use it with an x64 but none of them work.
Any chance that you provide a PactNet compatible with x86?

Thanks in advance for your help.

**Comment by adamrodger** [comment]
Unfortunately not - the shared FFI core is x64 only. The supported platforms and architectures are documented in the README and x86 is marked as not supported.
