### ISSUE TITLE
Add CI for Mac on Apple Sillicon

### ISSUE THREAD

**Issue by adamrodger** [pact-foundation/pact-net#451]
Depends on GitHub Actions feature https://github.com/github/roadmap/issues/528

Apple Sillicon (i.e. ARM64-based M1 and M2 processors) will only have alpha-level support until we can run CI fully on this OS/arch combination. This means that we ship the necessary binaries to make it work on a best-effort basis, but any bugs specific to that OS/arch may not be fixed until after this issue is resolved.

Alpha support was added in https://github.com/pact-foundation/pact-net/pull/365 and the binaries were included from [release 4.3.0](https://github.com/pact-foundation/pact-net/releases/tag/4.3.0)

**Comment by YOU54F** [comment]
Hey, 110% agree on this, but don't think we should wait until GitHub Actions adds the appropriate hardware as it might be a while.

Cirrus-CI offers the use of M1 mac's for free for public projects

It is pretty nice

https://cirrus-ci.org/guide/quick-start/

and can be hooked up with https://tart.run/ where a user can run the same CI run on their local machine (similar to https://github.com/nektos/act ) as long as they are running MacOS M1/M2 machines

They also offer the use of an ARM64 Linux Machine (as do CircleCI).

Wonder if it worth setting up an account per pact-foundation project (to avoid concurrency issues on the m1 resources)

As a non-scalable aside - I've managed to setup ephemeral runners on the mac m1 machine for linux/windows/mac github action runners, which at least allow for manual testing / validation of arm64 platforms.

**Comment by YOU54F** [comment]
>I'm not really looking to migrate CI off GitHub Actions currently because the support here is really good. The only problem being ARM-based Mac support.

Not suggesting we migrate everything, but we can add support for an m1 runner via cirrus, or another means for free, with a very easy way to test locally setup locally. Seems like a no brainer

>There was talk about the Pact Foundation paying for a self hosted ARM runner, but not sure where that's got to.

There is money in the pact-foundation kitty [open collective](https://opencollective.com/pact-foundation), however paid for m1 runners are prohibitively expensive from a cursory glance for my own personal needs (read: happy to use SaaS products, don't want to pay _any_ money 😅 )

With a community hat on, we would need someone to invest time in setting up the infra and ascertaining the usage/costs - we don't want a big bill we cant pay, its a fair point, and it's worth bringing up as we get together as a maintainer group to decide what is the best way forward.

I'm mainly talking from my own perspective here, I want things to be free and easy for the average user to run. Act is incredible for linux images, cirrus/tart offers free usage of m1 machines, very easy to setup ci, and plugs into github to report checks as per our existing github actions (so they could all remain as is)


>I'm not sure how much we can even officially support it ourselves anyway given ARM/Mac isn't a Tier 1 arch for Rust itself either. They're also waiting for GH to add ARM runners before they'll promote it from Tier 2. See: https://github.com/rust-lang/rust/issues/73908

Agreed, it's best efforts, official support of an open-source project is a grey area, even when it is a tier 1 arch, there will still be issues.

**Comment by YOU54F** [comment]
Working CI runs for 

- arm64/amd64 linux
- arm64 macos
  - with rosetta using x64 dotnet binaries
  - without rosetta using arm64 dotnet binaries

https://github.com/YOU54F/pact-net/blob/arm64_ci/.cirrus.yml
https://cirrus-ci.com/build/5775306234003456

**Comment by mefellows** [comment]
> There was talk about the Pact Foundation paying for a self hosted ARM runner, but not sure where that's got to.

Just on this - PactFlow/SmartBear are more than happy to supply the AWS runners for it (it just needs someone to create the GH custom agents I think).

But I think the solution Saf has proposed is much better!

**Comment by YOU54F** [comment]
FWIW I documented it here

https://docs.pact.io/contributing/ci

I like the fact that it is available for free to open source users, and therefore they have a path to contributing rather than being locked into to needing to potentially pay for aws runners if they want to replicate it on their own.

**Comment by mefellows** [comment]
Agree!

**Comment by TDavtyan-ST** [comment]
well, the day has come, and now it is added to github actions
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

**Comment by mefellows** [comment]
Yep! See also https://pact-foundation.slack.com/archives/C9VPNUJR2/p1706824238218649.

Yousaf has been adding runners to other projects, but I think we can progress this now. Open to a PR @TDavtyan-ST ? I'm assuming it should be straightforward.
