### ISSUE TITLE
Messaging - cannot configure ProviderStateMiddleware

### ISSUE THREAD

**Issue by DavidJFowler** [pact-foundation/pact-net#454]
There does not appear to be a straightforward way to configure provider state middleware for a messaging provider verifier and the ProviderStateMiddleware class in [samples/Messaging/Provider.Tests.ProviderStateMiddleware.cs](https://github.com/pact-foundation/pact-net/blob/master/samples/Messaging/Provider.Tests/ProviderStateMiddleware.cs) does not appear to be used.

**Comment by adamrodger** [comment]
That's something that you need to implement on an API somewhere yourself, then you point the verifier at wherever you've configured like this:

```csharp
verifier.MessagingProvider("My API")
        .WithProviderMessages(_ => {})
        .WithFileSource(...)
        .WithProviderStateUrl(new Uri("http://localhost:5000/provider-states"))
        .Verify()
```

The sample needs to have that class removed, it's probably just there from a copy and paste of the HTTP sample.
