### ISSUE TITLE
PactVerifierSource WithDirectorySource Method Not Work

### ISSUE THREAD

**Issue by alex-zinich** [pact-foundation/pact-net#456]
I have one pact test on my provider. I have a folder with different contracts with Consumer. When I run the test, it always passes, I tried changing the expected result in the contract, but the test still passed. After researching, I realized that the test does not send http requests, so it always passes.
The folder is not empty, it has the contract files. When I used another method: WithFileSource, the test started sending http requests and working.

![image](https://user-images.githubusercontent.com/101940942/235149646-84532d89-0a59-4d14-b1aa-6b1736268ee3.png)

**Comment by adamrodger** [comment]
Could you attach the contents of the directory and the output logs at Debug level please?

I assume that no matching pact files are being found due to naming differences or something, but the logs should tell us.

**Comment by alex-zinich** [comment]
![image](https://user-images.githubusercontent.com/101940942/235294093-6ac7a12b-09db-4f2b-80dd-e6ed340400ae.png)
![image](https://user-images.githubusercontent.com/101940942/235294300-da354d12-57d7-4546-960d-36b49dce0983.png)
![image](https://user-images.githubusercontent.com/101940942/235294379-ae75c455-8391-4662-b9e6-81376f1c453a.png)
![image](https://user-images.githubusercontent.com/101940942/235294403-dcb6e2be-ad35-41cf-98af-4f2a9b7892d7.png)
![image](https://user-images.githubusercontent.com/101940942/235294469-0e7cf136-d347-4bd6-8c6e-eee81057b0b8.png)

**Comment by adamrodger** [comment]
Have you edited the file name or the file contents? Neither of those match your test so wouldn't be used.

**Comment by adamrodger** [comment]
For example, the file says 'User_API' (with an underscore) whilst the test says 'User API' (with a space).

The file name is also not in the expected format of 'Consumer-Provider.json'

**Comment by alex-zinich** [comment]
Thanks a lot!
I don't knew about strong naming in test file, "provider" section
When I changed User API to User_API everything started working
