### ISSUE TITLE
Splitting provider tests across multiple classes

### ISSUE THREAD

**Issue by adrianhr91** [pact-foundation/pact-net#467]
I have a fairly large project where it would make sense to have certain provider tests broken up by their domain. After adding a second test class I realised Pact tries to validate all consumer tests in one go. Even though between the 2 classes I have full coverage.

The only thing I've found was to use the `.Filter()` method, which would've been fine but it means we can accidentally not cover consumer tests.

Am i missing something or is Pact expecting all provider tests to be written in the same class (or at least have one invocation point to verify everything)?

I've found this older thread which seems to suggest the same but because it was framed in a slightly different use-case so not sure if it is related https://github.com/pact-foundation/pact-net/issues/119

**Comment by adamrodger** [comment]
Yes, validation of a pact is a single operation per unique pair of provider and consumer. If you want to separate some tests out then you'd have to change the provider or consumer name.
