### ISSUE TITLE
dll.`s errors

### ISSUE THREAD

**Issue by Muscan** [pact-foundation/pact-net#473]
After cloning and run tests,  I got this error:

![image](https://github.com/pact-foundation/pact-net/assets/48117818/fd4c138c-b180-4e85-b044-3411ea0c7a39)

This is the line
![image](https://github.com/pact-foundation/pact-net/assets/48117818/d312f284-838e-4b1b-bce0-6ab614378d20)

And this error
![image](https://github.com/pact-foundation/pact-net/assets/48117818/6f4ee31e-1865-448e-8e60-4b3df7af9867)

I mention that I have he PactNet nuget and latest VS.
Thanks!

**Comment by YOU54F** [comment]
You need to download the libs if developing locally I believe

https://github.com/pact-foundation/pact-net/blob/master/build/download-native-libs.sh

**Comment by Muscan** [comment]
This sh was already downloaded at the clone. 
Checked the file, was there, just to double check, replace it. 
I ran this time the .sh script, and it downloaded a folder called windows. 
In that folder I needed to extract all files. 

After rebuild, I was able to run the tests. 
Thanks. 
Looking forward to provide some feedback!
![image](https://github.com/pact-foundation/pact-net/assets/48117818/73754278-bafb-4d2e-a47d-e026e85a9eaa)

**Comment by YOU54F** [comment]
Awesome thanks, looking forward to hearing you go. 

I am sure any attempt at contribution documentation would be useful, so your feedback will be useful!

Will close this down for now, feel free to jump in our slack.pact.io channels where we have a pact-net specific channel
