### ISSUE TITLE
Publish contracts to pact-broker using pactnet

### ISSUE THREAD

**Issue by marek2209** [pact-foundation/pact-net#474]
Is there are any way to publish contracts from code to pact broker. It seems like there is no such option.
https://github.com/pact-foundation/pact_broker ?

**Comment by YOU54F** [comment]
No it was dropped in pact-net v4 when moving onto the rust core,  meaning we didn't need to also add the legacy ruby executables, or recreate the functionality natively in .NET. The broker client functionality hasn't been ported to the rust core yet. It's a few api calls, so you could build some community based tooling. 

https://github.com/pact-foundation/pact-net/blob/master/docs/upgrading-to-4.md#other-changes

**Comment by mefellows** [comment]
Our current recommendation is to use https://docs.pact.io/implementation_guides/cli#pact-cli

**Comment by marek2209** [comment]
which workshop for pact-net on V3 is currently recommended to setup project
cór scratch?

W dniu pt., 8.09.2023 o 06:51 Matt Fellows ***@***.***>
napisał(a):

**Comment by YOU54F** [comment]
See comments here

https://github.com/pact-foundation/pact-net/issues/398#issuecomment-1523208824

These have been updated

- Updated https://github.com/pactflow/example-consumer-dotnet to use pact-net 4.x / .NET 6.0 and branches/environments/record deployments over tags
- Updated https://github.com/pactflow/example-provider-dotnet to use pact-net 4.x / .NET 6.0 and branches/environments/record deployments over tags
- https://github.com/pact-foundation/pact-workshop-dotnet-core-v1


This one

https://github.com/DiUS/pact-workshop-dotnet-core-v3

has a PR to update it [here](https://github.com/DiUS/pact-workshop-dotnet-core-v3/pulls)

I've incorporated updates ones into here at the moment

https://github.com/you54f/pact-workshops

Hope that helps a little bit. We would always be happy for examples to be shared back with the community or updated, and happy to help out if you for example create a public repo, try things out and get stuck, its super easy for others to jump in and collab

**Comment by marek2209** [comment]
should pact net use, database setup using testing containers framework or
just provider state?

W dniu pt., 8.09.2023 o 18:01 Yousaf Nabi ***@***.***>
napisał(a):

**Comment by mefellows** [comment]
> should pact net use, database setup using testing containers framework or
just provider state?

This is unrelated to the current issue, probably best discussed elsewhere (e.g. SO, slack.pact.io #pact-net channel). 

But TL;DR - Pact is agnostic to how you setup your state. Think of a state as a pre-condition for a test to pass, but it has not view on implementation of that.

**Comment by adamrodger** [comment]
The recommended way to publish pacts to the broker is using the Pact CLI tool linked above
