### ISSUE TITLE
ClearInteraction when using messaging pacts

### ISSUE THREAD

**Issue by singhvivek2503** [pact-foundation/pact-net#479]
I am using messaging pacts to contract test event based communication.
Is there a way similar to `_mockProviderServiceInstance.ClearInteractions();` when using messaging pacts?

```
this.pact = Pact.V4("ConsumerName", "ProviderName", config)
                .WithMessageInteractions();
```

**Comment by mefellows** [comment]
Why do you need to clear them?

**Comment by singhvivek2503** [comment]
> Why do you need to clear them?

Writing updated versions of old tests and adding new tests. The contract json file preserves the older interactions which I don't need anymore.

**Comment by mefellows** [comment]
Why does that matter? You shouldn't be uploading from a dirty development environment anyway.

If you need to clear old interactions, just delete the file

**Comment by adamrodger** [comment]
The ClearInteractions method was removed from PactNet in v4.x and is no longer required.

As @mefellows says, you should be starting each test run from a fresh environment with no existing Pact file so that older interactions aren't left behind.
