### ISSUE TITLE
PactV3Options Port value not respected

### ISSUE THREAD

**Issue by daTooz** [pact-foundation/pact-net#480]
I am attempting to new up a PactV3 using PactV3Options but it appears that the port property value is not respected...

> const provider = new PactV3({
>     consumer: "consumer",
>     provider: "provider",
>     //log: path.resolve(process.cwd(), "logs", "pact.log"),
>     //logLevel: "debug",
>     dir: path.resolve(process.cwd(), "pacts"),
>     spec: SpecificationVersion.SPECIFICATION_VERSION_V3,
>     host: "localhost",
>     port: 9999
> });

...whether or not the port value is set, the mockerserver is assigning a random port.

NOTES: 

1. The host value is respected.
2. "@pact-foundation/pact": "^12.1.0",
3. .Net Core 7.x

**Comment by YOU54F** [comment]
Hey, that is pact-js you are using and this is the pact-net repo. did you mean to raise this issue against https://github.com/pact-foundation/pact-js

**Comment by daTooz** [comment]
@YOU54F thank you for the prompt response. I am using pact-net and the behavior is exhibiting using C# .net 7. Thanks!

**Comment by YOU54F** [comment]
> 2. "@pact-foundation/pact": "^12.1.0",

This is pact-js

https://www.npmjs.com/package/@pact-foundation/pact


pact-nets packages are from nuget

https://www.nuget.org/packages/PactNet/


Your code snippet does not show .NET code

**Comment by daTooz** [comment]
Thank you! I have multiple IDEs open. You are correct. Thank you!
