### ISSUE TITLE
Pact-Net: PactConfig does not appear to have parity with Pact-JS - Missing [Host] and [Port] properties

### ISSUE THREAD

**Issue by daTooz** [pact-foundation/pact-net#482]
Request: Add [Host] and [Port] properties to Pact-Net PactConfig class.

Using pact-js, I can create a new pact where I can specify those properties...

> const provider = new Pact({
  consumer: "consumer-js-v2",
  provider: "provider-js-v2",
  host: "127.0.0.1",
  port: 9999
});
>

By comparison, I cannot specify those same properties in Pact-Net...

> var config = new PactConfig
{
	PactDir = PactDir,
	Outputters = new List<IOutput> { new XunitOutput(output), new ConsoleOutput() },
	LogLevel = PactLogLevel.Trace
};
_pact = PactNet.Pact.V3(_consumerName, _providerName, config).WithHttpInteractions();
>

**Comment by adamrodger** [comment]
The host and port are arguments to the WithHttpInteractions method
