### ISSUE TITLE
Pact Merging Creates Duplicate Interactions

### ISSUE THREAD

**Issue by adamrodger** [pact-foundation/pact-net#491]
**Version information:**
 - PactNet Version: 5.0.0-beta.2

**Describe the bug**
See https://github.com/pact-foundation/pact-reference/issues/389

**Additional context**
This blocks the full release of PactNet 5.0.0

**Comment by YOU54F** [comment]
fixed in 0.4.21 of the pact_ffi lib

**Comment by adamrodger** [comment]
Cool, thanks @YOU54F.  We'll look to upgrade and check out the differences.

**Comment by DavidJFowler** [comment]
Hi @adamrodger. Are you close to being able to release a GA version 5?

**Comment by adamrodger** [comment]
Fixed with an upgrade to FFI 0.4.23
