### ISSUE TITLE
RFC: Add Linux (libc)-ARM Runtime Support

### ISSUE THREAD

**Issue by dileepbg** [pact-foundation/pact-net#498]
**Previous issues**
Add Linux (libc)-ARM Runtime Support 

**Is your feature request related to a problem? Please describe.**
Currently we are planning to build and deploy our dotnet application on AWS graviton instances which are ARM arch based. While building the dotnet app on with ARM arch we are getting below error. As per the official documentation of this library it doesn't support Linux-ARM architecture yet.

System.DllNotFoundException : Unable to load shared library 'pact_ffi' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
Error loading shared library /usr/share/dotnet/shared/Microsoft.NETCore.App/8.0.5/pact_ffi.so: No such file or directory

**Describe the solution you'd like**
Need this library to be compatible with Linux-ARM

**Comment by adamrodger** [comment]
The FFI library does currently support Linux libc ARM binaries, so assuming
it's possibly to detect ARM when restoring the NuGet then this should be
straightforward to add.

**Comment by adamrodger** [comment]
Here are the methods for determining the runtime arch: 

https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation
