### ISSUE TITLE
Documentation Confusion

### ISSUE THREAD

**Issue by rcollette** [pact-foundation/pact-net#513]
If anyone else is coming here, using Pact version 4.5 and reading the README.md, be aware that you have to select the 4.x branch to see the documentation that goes with that release.   So contrary to every other repo I've seen, where the latest release is in master/main and the next release is some dev branch off of master/main.

Much wasted time trying to locate the current documentation.

**Comment by adamrodger** [comment]
I'm very sorry to hear you lost some time looking for the documentation for version 4.

The main branch is currently on v5 and the Readme contains links back to both the v3 and v4 documentation, as well as upgrade guides for how to migrate to v5.

It has these links that you can follow to view that documentation as well as the code as it was in those versions: 

![Screenshot_2024-07-17-21-49-51-43_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/user-attachments/assets/86b89cfb-9cf5-4067-91f4-ee157d84c447)

Hope that helps.
